// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Posting is one signed leg of a transaction. A positive amount is a debit, a
// negative amount is a credit. Amounts are minor units (for example cents).
// Currency is the posting's own currency: a cross-currency (FX) convert
// transaction spans two currencies, so each leg is labeled with its own
// rather than inheriting one shared transaction-level currency.
type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Posting) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Posting) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Posting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Posting) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// Transaction deliberately has no transaction-level currency field: a convert
// transaction spans two currencies, so a single top-level currency could
// never label every posting correctly. Each Posting carries its own instead.
type Transaction struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Postings []*Posting             `protobuf:"bytes,3,rep,name=postings,proto3" json:"postings,omitempty"`
	// reverses_transaction_id is set only when this transaction is itself a
	// reversal (Task 4.2, audit A1.2): the id of the transaction it reverses.
	// Empty for an ordinary post or convert.
	ReversesTransactionId string `protobuf:"bytes,4,opt,name=reverses_transaction_id,json=reversesTransactionId,proto3" json:"reverses_transaction_id,omitempty"`
	// reference is the caller's optional external id for reconciliation (Task
	// 4.3, audit A1.3), unique per tenant when present. Empty when the
	// transaction was posted without one.
	Reference string `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	// effective_at is the value date (Task 4.3, audit A1.3): when the
	// transaction is considered to have happened economically. Always set,
	// even when the caller supplied none: it then falls back to when the
	// transaction was actually posted. RFC3339 timestamp.
	EffectiveAt   string `protobuf:"bytes,6,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *Transaction) GetReversesTransactionId() string {
	if x != nil {
		return x.ReversesTransactionId
	}
	return ""
}

func (x *Transaction) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transaction) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

// status and min_balance are Task 5.5 (audit A1.5) additions: status is one
// of active, frozen, or closed; min_balance is the optional floor enforced
// on the account's derived balance, in minor units. min_balance is 0 when
// unset (proto3 has no distinct "absent" for a scalar int64), matching a
// literal 0 floor; a caller that needs to tell "no floor" apart from "floor
// of exactly zero" should use the REST API, whose min_balance is a JSON
// null-able field.
//
// party_reference and party_type (Task 6.1, audit A9.1) are optional
// linkage metadata for an external KYC/party system: an id and a free-text
// classification (e.g. "individual", "business"). Both are empty string
// when unset (proto3 has no distinct "absent" for a scalar string either); a
// caller that needs to tell "unset" apart from "an empty string was
// deliberately stored" should use the REST API instead, whose fields are
// JSON null-able. Neither is validated by this service beyond a length cap;
// the party/KYC system itself is external and out of scope.
type Account struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // asset, liability, equity, income, or expense
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	MinBalance     int64                  `protobuf:"varint,6,opt,name=min_balance,json=minBalance,proto3" json:"min_balance,omitempty"`
	PartyReference string                 `protobuf:"bytes,7,opt,name=party_reference,json=partyReference,proto3" json:"party_reference,omitempty"`
	PartyType      string                 `protobuf:"bytes,8,opt,name=party_type,json=partyType,proto3" json:"party_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetMinBalance() int64 {
	if x != nil {
		return x.MinBalance
	}
	return 0
}

func (x *Account) GetPartyReference() string {
	if x != nil {
		return x.PartyReference
	}
	return ""
}

func (x *Account) GetPartyType() string {
	if x != nil {
		return x.PartyType
	}
	return ""
}

// min_balance (Task 5.5, audit A1.5) is optional: 0 means no floor was
// requested, the same convention Account.min_balance above documents.
// party_reference and party_type (Task 6.1, audit A9.1) are optional too:
// empty string means neither was supplied, the same convention
// Account.party_reference/party_type above document.
type CreateAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	MinBalance     int64                  `protobuf:"varint,4,opt,name=min_balance,json=minBalance,proto3" json:"min_balance,omitempty"`
	PartyReference string                 `protobuf:"bytes,5,opt,name=party_reference,json=partyReference,proto3" json:"party_reference,omitempty"`
	PartyType      string                 `protobuf:"bytes,6,opt,name=party_type,json=partyType,proto3" json:"party_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetMinBalance() int64 {
	if x != nil {
		return x.MinBalance
	}
	return 0
}

func (x *CreateAccountRequest) GetPartyReference() string {
	if x != nil {
		return x.PartyReference
	}
	return ""
}

func (x *CreateAccountRequest) GetPartyType() string {
	if x != nil {
		return x.PartyType
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

// SetAccountStatusRequest freezes, closes, or reactivates one account (Task
// 5.5, audit A1.5), mirroring POST /v1/accounts/{id}/status.
type SetAccountStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // one of: active, frozen, closed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountStatusRequest) Reset() {
	*x = SetAccountStatusRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountStatusRequest) ProtoMessage() {}

func (x *SetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *SetAccountStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetAccountStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetAccountStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAccountStatusResponse) Reset() {
	*x = SetAccountStatusResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAccountStatusResponse) ProtoMessage() {}

func (x *SetAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*SetAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *SetAccountStatusResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *ListAccountsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetBalanceResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type StatementEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	RunningBalance int64                  `protobuf:"varint,4,opt,name=running_balance,json=runningBalance,proto3" json:"running_balance,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 timestamp
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatementEntry) Reset() {
	*x = StatementEntry{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementEntry) ProtoMessage() {}

func (x *StatementEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementEntry.ProtoReflect.Descriptor instead.
func (*StatementEntry) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *StatementEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatementEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *StatementEntry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StatementEntry) GetRunningBalance() int64 {
	if x != nil {
		return x.RunningBalance
	}
	return 0
}

func (x *StatementEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StatementEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetStatementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementRequest) Reset() {
	*x = GetStatementRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementRequest) ProtoMessage() {}

func (x *GetStatementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementRequest.ProtoReflect.Descriptor instead.
func (*GetStatementRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatementRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetStatementRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetStatementRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetStatementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Entries       []*StatementEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatementResponse) Reset() {
	*x = GetStatementResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatementResponse) ProtoMessage() {}

func (x *GetStatementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatementResponse.ProtoReflect.Descriptor instead.
func (*GetStatementResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatementResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetStatementResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetStatementResponse) GetEntries() []*StatementEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetStatementResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// PostTransactionRequest carries the balanced transaction. The idempotency key,
// when supplied, travels in the gRPC metadata key "idempotency-key", mirroring
// the REST Idempotency-Key header, not in this message.
type PostTransactionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Currency string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Postings []*Posting             `protobuf:"bytes,2,rep,name=postings,proto3" json:"postings,omitempty"`
	// reference is an optional external id for reconciliation (Task 4.3, audit
	// A1.3), unique per tenant when supplied. Reusing one already in use
	// returns ALREADY_EXISTS.
	Reference string `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	// effective_at is an optional value date (Task 4.3, audit A1.3), distinct
	// from when the row is actually written. Empty defaults to the post time.
	// RFC3339 timestamp.
	EffectiveAt   string `protobuf:"bytes,4,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTransactionRequest) Reset() {
	*x = PostTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTransactionRequest) ProtoMessage() {}

func (x *PostTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTransactionRequest.ProtoReflect.Descriptor instead.
func (*PostTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *PostTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PostTransactionRequest) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

func (x *PostTransactionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *PostTransactionRequest) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

type PostTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Replayed      bool                   `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTransactionResponse) Reset() {
	*x = PostTransactionResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTransactionResponse) ProtoMessage() {}

func (x *PostTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTransactionResponse.ProtoReflect.Descriptor instead.
func (*PostTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *PostTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *PostTransactionResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// ListTransactionsRequest lists the tenant's transactions, newest first,
// keyset paged by cursor, optionally filtered by a from/to created_at range
// and/or an exact reference match (Task 4.4, audit A7.2), mirroring GET
// /v1/transactions. from and to are RFC3339 timestamps; from is inclusive,
// to is exclusive. Export has no gRPC equivalent: a streaming CSV export
// does not fit gRPC's single-response model, so it stays REST-only.
type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{20}
}

func (x *ListTransactionsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListTransactionsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ListTransactionsRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ListTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTransactionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{21}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// ReverseTransactionRequest posts the negated legs of original_transaction_id
// as a new, linked transaction (Task 4.2, audit A1.2). Idempotent: a
// transaction can be reversed at most once, so calling this again for the
// same original returns the SAME reversal, with already_reversed = true,
// instead of posting a second one.
type ReverseTransactionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	OriginalTransactionId string                 `protobuf:"bytes,1,opt,name=original_transaction_id,json=originalTransactionId,proto3" json:"original_transaction_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReverseTransactionRequest) Reset() {
	*x = ReverseTransactionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionRequest) ProtoMessage() {}

func (x *ReverseTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionRequest.ProtoReflect.Descriptor instead.
func (*ReverseTransactionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{22}
}

func (x *ReverseTransactionRequest) GetOriginalTransactionId() string {
	if x != nil {
		return x.OriginalTransactionId
	}
	return ""
}

type ReverseTransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	AlreadyReversed bool                   `protobuf:"varint,2,opt,name=already_reversed,json=alreadyReversed,proto3" json:"already_reversed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReverseTransactionResponse) Reset() {
	*x = ReverseTransactionResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReverseTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseTransactionResponse) ProtoMessage() {}

func (x *ReverseTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseTransactionResponse.ProtoReflect.Descriptor instead.
func (*ReverseTransactionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{23}
}

func (x *ReverseTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ReverseTransactionResponse) GetAlreadyReversed() bool {
	if x != nil {
		return x.AlreadyReversed
	}
	return false
}

type AuditEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Actor         string                 `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Before        string                 `protobuf:"bytes,5,opt,name=before,proto3" json:"before,omitempty"`                        // raw JSON, may be empty for a create
	After         string                 `protobuf:"bytes,6,opt,name=after,proto3" json:"after,omitempty"`                          // raw JSON snapshot
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{24}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *AuditEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *AuditEntry) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *AuditEntry) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *AuditEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTransactionAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionAuditRequest) Reset() {
	*x = GetTransactionAuditRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionAuditRequest) ProtoMessage() {}

func (x *GetTransactionAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionAuditRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionAuditRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{25}
}

func (x *GetTransactionAuditRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetTransactionAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionAuditResponse) Reset() {
	*x = GetTransactionAuditResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionAuditResponse) ProtoMessage() {}

func (x *GetTransactionAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionAuditResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionAuditResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{26}
}

func (x *GetTransactionAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetAccountAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountAuditRequest) Reset() {
	*x = GetAccountAuditRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAuditRequest) ProtoMessage() {}

func (x *GetAccountAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAuditRequest.ProtoReflect.Descriptor instead.
func (*GetAccountAuditRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{27}
}

func (x *GetAccountAuditRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountAuditRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAccountAuditRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GetAccountAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountAuditResponse) Reset() {
	*x = GetAccountAuditResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountAuditResponse) ProtoMessage() {}

func (x *GetAccountAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountAuditResponse.ProtoReflect.Descriptor instead.
func (*GetAccountAuditResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{28}
}

func (x *GetAccountAuditResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetAccountAuditResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// FXDetail is the applied-rate detail for a cross-currency convert: the
// requested and converted amounts, the mid rate and spread applied, and
// where that rate came from (ADR-014 decision 7).
type FXDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceAmount    int64                  `protobuf:"varint,1,opt,name=source_amount,json=sourceAmount,proto3" json:"source_amount,omitempty"`
	ConvertedAmount int64                  `protobuf:"varint,2,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	MidRateE8       int64                  `protobuf:"varint,3,opt,name=mid_rate_e8,json=midRateE8,proto3" json:"mid_rate_e8,omitempty"`
	AppliedE8       int64                  `protobuf:"varint,4,opt,name=applied_e8,json=appliedE8,proto3" json:"applied_e8,omitempty"`
	SpreadBps       int32                  `protobuf:"varint,5,opt,name=spread_bps,json=spreadBps,proto3" json:"spread_bps,omitempty"`
	RateSource      string                 `protobuf:"bytes,6,opt,name=rate_source,json=rateSource,proto3" json:"rate_source,omitempty"`
	EffectiveAt     string                 `protobuf:"bytes,7,opt,name=effective_at,json=effectiveAt,proto3" json:"effective_at,omitempty"` // RFC3339 timestamp
	RateId          int64                  `protobuf:"varint,8,opt,name=rate_id,json=rateId,proto3" json:"rate_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FXDetail) Reset() {
	*x = FXDetail{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FXDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FXDetail) ProtoMessage() {}

func (x *FXDetail) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FXDetail.ProtoReflect.Descriptor instead.
func (*FXDetail) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{29}
}

func (x *FXDetail) GetSourceAmount() int64 {
	if x != nil {
		return x.SourceAmount
	}
	return 0
}

func (x *FXDetail) GetConvertedAmount() int64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *FXDetail) GetMidRateE8() int64 {
	if x != nil {
		return x.MidRateE8
	}
	return 0
}

func (x *FXDetail) GetAppliedE8() int64 {
	if x != nil {
		return x.AppliedE8
	}
	return 0
}

func (x *FXDetail) GetSpreadBps() int32 {
	if x != nil {
		return x.SpreadBps
	}
	return 0
}

func (x *FXDetail) GetRateSource() string {
	if x != nil {
		return x.RateSource
	}
	return ""
}

func (x *FXDetail) GetEffectiveAt() string {
	if x != nil {
		return x.EffectiveAt
	}
	return ""
}

func (x *FXDetail) GetRateId() int64 {
	if x != nil {
		return x.RateId
	}
	return 0
}

// ConvertRequest converts source_amount from the from_account's currency into
// the to_account's currency, at the tenant's current FX rate. The
// idempotency key, when supplied, travels in the gRPC metadata key
// "idempotency-key", the same as PostTransactionRequest, not in this message.
// The destination currency always comes from the to account: a client cannot
// supply a rate or target currency directly.
type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccount   string                 `protobuf:"bytes,1,opt,name=from_account,json=fromAccount,proto3" json:"from_account,omitempty"`
	ToAccount     string                 `protobuf:"bytes,2,opt,name=to_account,json=toAccount,proto3" json:"to_account,omitempty"`
	SourceAmount  int64                  `protobuf:"varint,3,opt,name=source_amount,json=sourceAmount,proto3" json:"source_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{30}
}

func (x *ConvertRequest) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *ConvertRequest) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *ConvertRequest) GetSourceAmount() int64 {
	if x != nil {
		return x.SourceAmount
	}
	return 0
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Fx            *FXDetail              `protobuf:"bytes,2,opt,name=fx,proto3" json:"fx,omitempty"`
	Replayed      bool                   `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{31}
}

func (x *ConvertResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ConvertResponse) GetFx() *FXDetail {
	if x != nil {
		return x.Fx
	}
	return nil
}

func (x *ConvertResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\tledger.v1\"~\n" +
	"\aPosting\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xd6\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\bpostings\x18\x03 \x03(\v2\x12.ledger.v1.PostingR\bpostings\x126\n" +
	"\x17reverses_transaction_id\x18\x04 \x01(\tR\x15reversesTransactionId\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\x12!\n" +
	"\feffective_at\x18\x06 \x01(\tR\veffectiveAtJ\x04\b\x02\x10\x03R\bcurrency\"\xde\x01\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vmin_balance\x18\x06 \x01(\x03R\n" +
	"minBalance\x12'\n" +
	"\x0fparty_reference\x18\a \x01(\tR\x0epartyReference\x12\x1d\n" +
	"\n" +
	"party_type\x18\b \x01(\tR\tpartyType\"\xc3\x01\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vmin_balance\x18\x04 \x01(\x03R\n" +
	"minBalance\x12'\n" +
	"\x0fparty_reference\x18\x05 \x01(\tR\x0epartyReference\x12\x1d\n" +
	"\n" +
	"party_type\x18\x06 \x01(\tR\tpartyType\"E\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x12GetAccountResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"A\n" +
	"\x17SetAccountStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"H\n" +
	"\x18SetAccountStatusResponse\x12,\n" +
	"\aaccount\x18\x01 \x01(\v2\x12.ledger.v1.AccountR\aaccount\"+\n" +
	"\x13ListAccountsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"F\n" +
	"\x14ListAccountsResponse\x12.\n" +
	"\baccounts\x18\x01 \x03(\v2\x12.ledger.v1.AccountR\baccounts\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"g\n" +
	"\x12GetBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xc9\x01\n" +
	"\x0eStatementEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0frunning_balance\x18\x04 \x01(\x03R\x0erunningBalance\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"b\n" +
	"\x13GetStatementRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xa7\x01\n" +
	"\x14GetStatementResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x123\n" +
	"\aentries\x18\x03 \x03(\v2\x19.ledger.v1.StatementEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\"\xa5\x01\n" +
	"\x16PostTransactionRequest\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12.\n" +
	"\bpostings\x18\x02 \x03(\v2\x12.ledger.v1.PostingR\bpostings\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12!\n" +
	"\feffective_at\x18\x04 \x01(\tR\veffectiveAt\"o\n" +
	"\x17PostTransactionResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x16GetTransactionResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\"\x89\x01\n" +
	"\x17ListTransactionsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"w\n" +
	"\x18ListTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.ledger.v1.TransactionR\ftransactions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"S\n" +
	"\x19ReverseTransactionRequest\x126\n" +
	"\x17original_transaction_id\x18\x01 \x01(\tR\x15originalTransactionId\"\x81\x01\n" +
	"\x1aReverseTransactionResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\x12)\n" +
	"\x10already_reversed\x18\x02 \x01(\bR\x0falreadyReversed\"\xbe\x01\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x16\n" +
	"\x06before\x18\x05 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x06 \x01(\tR\x05after\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"C\n" +
	"\x1aGetTransactionAuditRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"N\n" +
	"\x1bGetTransactionAuditResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.ledger.v1.AuditEntryR\aentries\"e\n" +
	"\x16GetAccountAuditRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"k\n" +
	"\x17GetAccountAuditResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.ledger.v1.AuditEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x95\x02\n" +
	"\bFXDetail\x12#\n" +
	"\rsource_amount\x18\x01 \x01(\x03R\fsourceAmount\x12)\n" +
	"\x10converted_amount\x18\x02 \x01(\x03R\x0fconvertedAmount\x12\x1e\n" +
	"\vmid_rate_e8\x18\x03 \x01(\x03R\tmidRateE8\x12\x1d\n" +
	"\n" +
	"applied_e8\x18\x04 \x01(\x03R\tappliedE8\x12\x1d\n" +
	"\n" +
	"spread_bps\x18\x05 \x01(\x05R\tspreadBps\x12\x1f\n" +
	"\vrate_source\x18\x06 \x01(\tR\n" +
	"rateSource\x12!\n" +
	"\feffective_at\x18\a \x01(\tR\veffectiveAt\x12\x17\n" +
	"\arate_id\x18\b \x01(\x03R\x06rateId\"w\n" +
	"\x0eConvertRequest\x12!\n" +
	"\ffrom_account\x18\x01 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x02 \x01(\tR\ttoAccount\x12#\n" +
	"\rsource_amount\x18\x03 \x01(\x03R\fsourceAmount\"\x8c\x01\n" +
	"\x0fConvertResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.ledger.v1.TransactionR\vtransaction\x12#\n" +
	"\x02fx\x18\x02 \x01(\v2\x13.ledger.v1.FXDetailR\x02fx\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed2\xeb\b\n" +
	"\rLedgerService\x12R\n" +
	"\rCreateAccount\x12\x1f.ledger.v1.CreateAccountRequest\x1a .ledger.v1.CreateAccountResponse\x12I\n" +
	"\n" +
	"GetAccount\x12\x1c.ledger.v1.GetAccountRequest\x1a\x1d.ledger.v1.GetAccountResponse\x12[\n" +
	"\x10SetAccountStatus\x12\".ledger.v1.SetAccountStatusRequest\x1a#.ledger.v1.SetAccountStatusResponse\x12O\n" +
	"\fListAccounts\x12\x1e.ledger.v1.ListAccountsRequest\x1a\x1f.ledger.v1.ListAccountsResponse\x12I\n" +
	"\n" +
	"GetBalance\x12\x1c.ledger.v1.GetBalanceRequest\x1a\x1d.ledger.v1.GetBalanceResponse\x12O\n" +
	"\fGetStatement\x12\x1e.ledger.v1.GetStatementRequest\x1a\x1f.ledger.v1.GetStatementResponse\x12X\n" +
	"\x0fPostTransaction\x12!.ledger.v1.PostTransactionRequest\x1a\".ledger.v1.PostTransactionResponse\x12@\n" +
	"\aConvert\x12\x19.ledger.v1.ConvertRequest\x1a\x1a.ledger.v1.ConvertResponse\x12U\n" +
	"\x0eGetTransaction\x12 .ledger.v1.GetTransactionRequest\x1a!.ledger.v1.GetTransactionResponse\x12[\n" +
	"\x10ListTransactions\x12\".ledger.v1.ListTransactionsRequest\x1a#.ledger.v1.ListTransactionsResponse\x12a\n" +
	"\x12ReverseTransaction\x12$.ledger.v1.ReverseTransactionRequest\x1a%.ledger.v1.ReverseTransactionResponse\x12d\n" +
	"\x13GetTransactionAudit\x12%.ledger.v1.GetTransactionAuditRequest\x1a&.ledger.v1.GetTransactionAuditResponse\x12X\n" +
	"\x0fGetAccountAudit\x12!.ledger.v1.GetAccountAuditRequest\x1a\".ledger.v1.GetAccountAuditResponseB\xa6\x01\n" +
	"\rcom.ledger.v1B\vLedgerProtoP\x01ZCgithub.com/sohag-pro/go-ledger/internal/genproto/ledger/v1;ledgerv1\xa2\x02\x03LXX\xaa\x02\tLedger.V1\xca\x02\tLedger\\V1\xe2\x02\x15Ledger\\V1\\GPBMetadata\xea\x02\n" +
	"Ledger::V1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(*Posting)(nil),                     // 0: ledger.v1.Posting
	(*Transaction)(nil),                 // 1: ledger.v1.Transaction
	(*Account)(nil),                     // 2: ledger.v1.Account
	(*CreateAccountRequest)(nil),        // 3: ledger.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 4: ledger.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),           // 5: ledger.v1.GetAccountRequest
	(*GetAccountResponse)(nil),          // 6: ledger.v1.GetAccountResponse
	(*SetAccountStatusRequest)(nil),     // 7: ledger.v1.SetAccountStatusRequest
	(*SetAccountStatusResponse)(nil),    // 8: ledger.v1.SetAccountStatusResponse
	(*ListAccountsRequest)(nil),         // 9: ledger.v1.ListAccountsRequest
	(*ListAccountsResponse)(nil),        // 10: ledger.v1.ListAccountsResponse
	(*GetBalanceRequest)(nil),           // 11: ledger.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),          // 12: ledger.v1.GetBalanceResponse
	(*StatementEntry)(nil),              // 13: ledger.v1.StatementEntry
	(*GetStatementRequest)(nil),         // 14: ledger.v1.GetStatementRequest
	(*GetStatementResponse)(nil),        // 15: ledger.v1.GetStatementResponse
	(*PostTransactionRequest)(nil),      // 16: ledger.v1.PostTransactionRequest
	(*PostTransactionResponse)(nil),     // 17: ledger.v1.PostTransactionResponse
	(*GetTransactionRequest)(nil),       // 18: ledger.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),      // 19: ledger.v1.GetTransactionResponse
	(*ListTransactionsRequest)(nil),     // 20: ledger.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),    // 21: ledger.v1.ListTransactionsResponse
	(*ReverseTransactionRequest)(nil),   // 22: ledger.v1.ReverseTransactionRequest
	(*ReverseTransactionResponse)(nil),  // 23: ledger.v1.ReverseTransactionResponse
	(*AuditEntry)(nil),                  // 24: ledger.v1.AuditEntry
	(*GetTransactionAuditRequest)(nil),  // 25: ledger.v1.GetTransactionAuditRequest
	(*GetTransactionAuditResponse)(nil), // 26: ledger.v1.GetTransactionAuditResponse
	(*GetAccountAuditRequest)(nil),      // 27: ledger.v1.GetAccountAuditRequest
	(*GetAccountAuditResponse)(nil),     // 28: ledger.v1.GetAccountAuditResponse
	(*FXDetail)(nil),                    // 29: ledger.v1.FXDetail
	(*ConvertRequest)(nil),              // 30: ledger.v1.ConvertRequest
	(*ConvertResponse)(nil),             // 31: ledger.v1.ConvertResponse
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: ledger.v1.Transaction.postings:type_name -> ledger.v1.Posting
	2,  // 1: ledger.v1.CreateAccountResponse.account:type_name -> ledger.v1.Account
	2,  // 2: ledger.v1.GetAccountResponse.account:type_name -> ledger.v1.Account
	2,  // 3: ledger.v1.SetAccountStatusResponse.account:type_name -> ledger.v1.Account
	2,  // 4: ledger.v1.ListAccountsResponse.accounts:type_name -> ledger.v1.Account
	13, // 5: ledger.v1.GetStatementResponse.entries:type_name -> ledger.v1.StatementEntry
	0,  // 6: ledger.v1.PostTransactionRequest.postings:type_name -> ledger.v1.Posting
	1,  // 7: ledger.v1.PostTransactionResponse.transaction:type_name -> ledger.v1.Transaction
	1,  // 8: ledger.v1.GetTransactionResponse.transaction:type_name -> ledger.v1.Transaction
	1,  // 9: ledger.v1.ListTransactionsResponse.transactions:type_name -> ledger.v1.Transaction
	1,  // 10: ledger.v1.ReverseTransactionResponse.transaction:type_name -> ledger.v1.Transaction
	24, // 11: ledger.v1.GetTransactionAuditResponse.entries:type_name -> ledger.v1.AuditEntry
	24, // 12: ledger.v1.GetAccountAuditResponse.entries:type_name -> ledger.v1.AuditEntry
	1,  // 13: ledger.v1.ConvertResponse.transaction:type_name -> ledger.v1.Transaction
	29, // 14: ledger.v1.ConvertResponse.fx:type_name -> ledger.v1.FXDetail
	3,  // 15: ledger.v1.LedgerService.CreateAccount:input_type -> ledger.v1.CreateAccountRequest
	5,  // 16: ledger.v1.LedgerService.GetAccount:input_type -> ledger.v1.GetAccountRequest
	7,  // 17: ledger.v1.LedgerService.SetAccountStatus:input_type -> ledger.v1.SetAccountStatusRequest
	9,  // 18: ledger.v1.LedgerService.ListAccounts:input_type -> ledger.v1.ListAccountsRequest
	11, // 19: ledger.v1.LedgerService.GetBalance:input_type -> ledger.v1.GetBalanceRequest
	14, // 20: ledger.v1.LedgerService.GetStatement:input_type -> ledger.v1.GetStatementRequest
	16, // 21: ledger.v1.LedgerService.PostTransaction:input_type -> ledger.v1.PostTransactionRequest
	30, // 22: ledger.v1.LedgerService.Convert:input_type -> ledger.v1.ConvertRequest
	18, // 23: ledger.v1.LedgerService.GetTransaction:input_type -> ledger.v1.GetTransactionRequest
	20, // 24: ledger.v1.LedgerService.ListTransactions:input_type -> ledger.v1.ListTransactionsRequest
	22, // 25: ledger.v1.LedgerService.ReverseTransaction:input_type -> ledger.v1.ReverseTransactionRequest
	25, // 26: ledger.v1.LedgerService.GetTransactionAudit:input_type -> ledger.v1.GetTransactionAuditRequest
	27, // 27: ledger.v1.LedgerService.GetAccountAudit:input_type -> ledger.v1.GetAccountAuditRequest
	4,  // 28: ledger.v1.LedgerService.CreateAccount:output_type -> ledger.v1.CreateAccountResponse
	6,  // 29: ledger.v1.LedgerService.GetAccount:output_type -> ledger.v1.GetAccountResponse
	8,  // 30: ledger.v1.LedgerService.SetAccountStatus:output_type -> ledger.v1.SetAccountStatusResponse
	10, // 31: ledger.v1.LedgerService.ListAccounts:output_type -> ledger.v1.ListAccountsResponse
	12, // 32: ledger.v1.LedgerService.GetBalance:output_type -> ledger.v1.GetBalanceResponse
	15, // 33: ledger.v1.LedgerService.GetStatement:output_type -> ledger.v1.GetStatementResponse
	17, // 34: ledger.v1.LedgerService.PostTransaction:output_type -> ledger.v1.PostTransactionResponse
	31, // 35: ledger.v1.LedgerService.Convert:output_type -> ledger.v1.ConvertResponse
	19, // 36: ledger.v1.LedgerService.GetTransaction:output_type -> ledger.v1.GetTransactionResponse
	21, // 37: ledger.v1.LedgerService.ListTransactions:output_type -> ledger.v1.ListTransactionsResponse
	23, // 38: ledger.v1.LedgerService.ReverseTransaction:output_type -> ledger.v1.ReverseTransactionResponse
	26, // 39: ledger.v1.LedgerService.GetTransactionAudit:output_type -> ledger.v1.GetTransactionAuditResponse
	28, // 40: ledger.v1.LedgerService.GetAccountAudit:output_type -> ledger.v1.GetAccountAuditResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
