// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalances = `-- name: AccountBalances :many
SELECT a.id, COALESCE(SUM(p.amount), 0)::bigint AS balance
FROM accounts a
LEFT JOIN postings p ON p.tenant_id = a.tenant_id AND p.account_id = a.id
WHERE a.tenant_id = $1 AND a.id = ANY($2::uuid[])
GROUP BY a.id
`

type AccountBalancesParams struct {
	TenantID   uuid.UUID
	AccountIds []uuid.UUID
}

type AccountBalancesRow struct {
	ID      uuid.UUID
	Balance int64
}

// Task 5.5, audit A1.5: each named account's derived balance, read inside
// the caller's SERIALIZABLE RunInTx body so it is consistent with the
// CreateTransaction write that follows in the same transaction: two
// concurrent posts that would each individually keep an account above its
// floor, but together breach it, are a genuine read-write antidependency
// SERIALIZABLE detects and aborts one of. Called ONLY for accounts that
// AccountStatusFlags reported as having a MinBalance configured (see
// AccountStatusFlags's own doc comment for why this query is kept separate
// and only run when actually needed). The LEFT JOIN (rather than a subquery
// per account) means an account with no postings yet still returns one row,
// with balance COALESCEd to 0.
func (q *Queries) AccountBalances(ctx context.Context, arg AccountBalancesParams) ([]AccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, accountBalances, arg.TenantID, arg.AccountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBalancesRow
	for rows.Next() {
		var i AccountBalancesRow
		if err := rows.Scan(&i.ID, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accountStatusFlags = `-- name: AccountStatusFlags :many
SELECT id, status, min_balance, is_system
FROM accounts
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

type AccountStatusFlagsParams struct {
	TenantID   uuid.UUID
	AccountIds []uuid.UUID
}

type AccountStatusFlagsRow struct {
	ID         uuid.UUID
	Status     string
	MinBalance pgtype.Int8
	IsSystem   bool
}

// Task 5.5, audit A1.5: each named account's current status, min_balance,
// and is_system flag ONLY (no balance), read inside the caller's
// SERIALIZABLE RunInTx body (see domain.Tx.AccountPostingStates). This is
// deliberately split from AccountBalances below: this query touches only the
// accounts table, which nothing in the posting path ever writes to (a post
// inserts into transactions/postings/audit_outbox/idempotency_keys, never
// accounts), so it can never be the read side of a SERIALIZABLE read-write
// antidependency against a concurrent post. That is exactly what a combined
// query joining postings would risk: reading every historical posting for a
// hot account inside the same transaction as a concurrent INSERT into that
// account's postings is precisely the kind of broad read-write overlap
// SERIALIZABLE flags, and doing it unconditionally on every single post
// (unlike the opt-in TenantDailyDebits check) reintroduced, under many-way
// single-tenant concurrency onto a handful of accounts, the same class of
// retry storm ADR-017 removed the audit chain read to get rid of (see
// TestPostConcurrentStressSingleTenant). AccountBalances is now only ever
// called for the subset of accounts that actually have a MinBalance set.
func (q *Queries) AccountStatusFlags(ctx context.Context, arg AccountStatusFlagsParams) ([]AccountStatusFlagsRow, error) {
	rows, err := q.db.Query(ctx, accountStatusFlags, arg.TenantID, arg.AccountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountStatusFlagsRow
	for rows.Next() {
		var i AccountStatusFlagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.MinBalance,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const allAccountBalances = `-- name: AllAccountBalances :many
SELECT a.id, a.tenant_id, a.name, a.type, a.currency, a.status, a.min_balance,
       a.is_system, a.created_at, a.party_reference, a.party_type, a.parent_id,
       COALESCE(SUM(p.amount), 0)::bigint AS balance
FROM accounts a
LEFT JOIN postings p ON p.tenant_id = a.tenant_id AND p.account_id = a.id
WHERE a.tenant_id = $1
GROUP BY a.id, a.tenant_id, a.name, a.type, a.currency, a.status, a.min_balance,
         a.is_system, a.created_at, a.party_reference, a.party_type, a.parent_id
ORDER BY a.name, a.id
LIMIT 10001
`

type AllAccountBalancesRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	Status         string
	MinBalance     pgtype.Int8
	IsSystem       bool
	CreatedAt      time.Time
	PartyReference pgtype.Text
	PartyType      pgtype.Text
	ParentID       pgtype.UUID
	Balance        int64
}

// Every account for a tenant with its own derived balance (LEFT JOIN so an
// account with no postings returns 0) and its parent_id, so the caller can
// build the tree and roll up in memory in one pass. Ordered by name, id for a
// stable base order the Go rollup then re-threads parent-before-child.
// Bounded read (audit remediation): one more than ledger.MaxReportRows, so the
// service can detect "too large for a single unpaged response" and refuse
// rather than stream an unbounded result set into memory. Keep in sync with
// ledger.MaxReportRows.
func (q *Queries) AllAccountBalances(ctx context.Context, tenantID uuid.UUID) ([]AllAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, allAccountBalances, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AllAccountBalancesRow
	for rows.Next() {
		var i AllAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Status,
			&i.MinBalance,
			&i.IsSystem,
			&i.CreatedAt,
			&i.PartyReference,
			&i.PartyType,
			&i.ParentID,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, tenant_id, name, type, currency, min_balance, party_reference, party_type, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAccountParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	MinBalance     pgtype.Int8
	PartyReference pgtype.Text
	PartyType      pgtype.Text
	ParentID       pgtype.UUID
}

// min_balance (Task 5.5, audit A1.5), party_reference, and party_type (Task
// 6.1, audit A9.1) are all nullable: sqlc.narg leaves each unset (NULL) when
// the caller passes no value, matching "no floor configured" / "no party
// linkage supplied", every account's behavior before these columns existed.
// status is NOT inserted explicitly: the column default ('active', migration
// 0022) applies, the same way CreateTenant leaves status to the column
// default.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.MinBalance,
		arg.PartyReference,
		arg.PartyType,
		arg.ParentID,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, name, type, currency, status, min_balance, is_system, created_at, party_reference, party_type, parent_id
FROM accounts
WHERE tenant_id = $1 AND id = $2
`

type GetAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetAccountRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	Status         string
	MinBalance     pgtype.Int8
	IsSystem       bool
	CreatedAt      time.Time
	PartyReference pgtype.Text
	PartyType      pgtype.Text
	ParentID       pgtype.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.ID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.MinBalance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.PartyReference,
		&i.PartyType,
		&i.ParentID,
	)
	return i, err
}

const getOrCreateClearingAccount = `-- name: GetOrCreateClearingAccount :one
INSERT INTO accounts (id, tenant_id, name, type, currency, is_system)
VALUES ($1, $2, $3, $4, $5, true)
ON CONFLICT (tenant_id, name) WHERE is_system
    DO UPDATE SET id = accounts.id
RETURNING id, tenant_id, name, type, currency, status, min_balance, is_system, created_at, party_reference, party_type
`

type GetOrCreateClearingAccountParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Type     string
	Currency string
}

type GetOrCreateClearingAccountRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	Status         string
	MinBalance     pgtype.Int8
	IsSystem       bool
	CreatedAt      time.Time
	PartyReference pgtype.Text
	PartyType      pgtype.Text
}

// The per-tenant per-currency FX clearing account (ADR-014, is_system=true),
// created lazily on first use. Keyed by (tenant_id, name): name is the
// reserved, deterministic "fx.clearing.<CURRENCY>" string the caller builds,
// so a second call for the same tenant and currency always resolves to the
// same row instead of creating a duplicate. The ON CONFLICT arbiter is the
// partial unique index accounts_system_name_uniq (migration 0010), which only
// covers is_system rows, so this can never collide with an ordinary
// user-named account.
//
// On conflict this does a no-op DO UPDATE (id set to its own current value)
// rather than DO NOTHING. DO NOTHING never RETURNs the conflicting row, which
// an earlier version of this query worked around with a CTE plus a fallback
// SELECT unioned into the same statement, guarded by NOT EXISTS. That
// fallback ran against the single statement's original snapshot: when two
// callers raced to create the same tenant's first clearing account for a
// currency, the loser blocked on the conflict, and by the time it unblocked
// (after the winner committed) its own fallback SELECT could still miss the
// now-committed row, since the snapshot predated that commit. Both branches
// of the UNION then returned zero rows to the loser, surfacing as "no rows in
// result set" under concurrent Converts targeting the same pair. DO UPDATE
// instead forces Postgres's own EvalPlanQual re-fetch of the current row
// version as part of resolving the conflict, so RETURNING always yields
// exactly one row, new or existing, in a single round trip with no second
// snapshot to race against.
func (q *Queries) GetOrCreateClearingAccount(ctx context.Context, arg GetOrCreateClearingAccountParams) (GetOrCreateClearingAccountRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateClearingAccount,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	var i GetOrCreateClearingAccountRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Status,
		&i.MinBalance,
		&i.IsSystem,
		&i.CreatedAt,
		&i.PartyReference,
		&i.PartyType,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, name, type, currency, status, min_balance, is_system, created_at, party_reference, party_type, parent_id
FROM accounts
WHERE tenant_id = $1
ORDER BY name, id
LIMIT $2
`

type ListAccountsParams struct {
	TenantID uuid.UUID
	Limit    int32
}

type ListAccountsRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	Status         string
	MinBalance     pgtype.Int8
	IsSystem       bool
	CreatedAt      time.Time
	PartyReference pgtype.Text
	PartyType      pgtype.Text
	ParentID       pgtype.UUID
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsRow
	for rows.Next() {
		var i ListAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Status,
			&i.MinBalance,
			&i.IsSystem,
			&i.CreatedAt,
			&i.PartyReference,
			&i.PartyType,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolledUpBalance = `-- name: RolledUpBalance :one
WITH RECURSIVE subtree AS (
  SELECT a.id FROM accounts a WHERE a.tenant_id = $1 AND a.id = $2
  UNION ALL
  SELECT a.id FROM accounts a
    JOIN subtree s ON a.parent_id = s.id AND a.tenant_id = $1
)
SELECT COALESCE(SUM(p.amount), 0)::bigint AS balance
FROM postings p
WHERE p.tenant_id = $1 AND p.account_id IN (SELECT id FROM subtree)
`

type RolledUpBalanceParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// The balance of an account and everything under it: gather the subtree via
// parent_id, then sum those accounts' postings. Same-currency subtree, so this
// is one number.
func (q *Queries) RolledUpBalance(ctx context.Context, arg RolledUpBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, rolledUpBalance, arg.TenantID, arg.ID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const setAccountParent = `-- name: SetAccountParent :execrows
UPDATE accounts SET parent_id = $3
WHERE tenant_id = $1 AND id = $2
`

type SetAccountParentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	ParentID pgtype.UUID
}

// Re-parent (or clear, when parent_id is NULL) one account. Cycle, currency,
// and same-tenant are enforced by accounts_hierarchy_guard / the composite FK.
func (q *Queries) SetAccountParent(ctx context.Context, arg SetAccountParentParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountParent, arg.TenantID, arg.ID, arg.ParentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccountStatus = `-- name: SetAccountStatus :execrows
UPDATE accounts SET status = $3
WHERE tenant_id = $1 AND id = $2
`

type SetAccountStatusParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
	Status   string
}

// Task 5.5, audit A1.5: freezes, closes, or reactivates one account. Scoped
// to tenant_id like every other write here, so a caller can never flip a
// status on another tenant's account by id alone.
func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccountStatus, arg.TenantID, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
