// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, tenant_id, name, type, currency)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAccountParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Type     string
	Currency string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Currency,
	)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, name, type, currency, created_at
FROM accounts
WHERE tenant_id = $1 AND id = $2
`

type GetAccountParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.TenantID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
