// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT api_keys.id, api_keys.tenant_id, api_keys.name, api_keys.rate_limit_rpm, api_keys.created_at, api_keys.revoked_at,
       tenants.status AS tenant_status
FROM api_keys
JOIN tenants ON tenants.id = api_keys.tenant_id
WHERE api_keys.key_hash = $1 AND api_keys.revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	TenantStatus string
}

// Joins tenants so the resolver gets the tenant's current status alongside
// the key in the same round trip (Task 2.1, ADR-015): gating needs no extra
// query. The join is safe against a dangling reference: api_keys_tenant_fk
// (migration 0011) guarantees every api_keys row's tenant_id has a tenants
// row.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RateLimitRpm,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.TenantStatus,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (id, tenant_id, name, key_hash, rate_limit_rpm)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAPIKeyParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	KeyHash      string
	RateLimitRpm pgtype.Int4
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.RateLimitRpm,
	)
	return err
}
