// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT api_keys.id, api_keys.tenant_id, api_keys.name, api_keys.rate_limit_rpm, api_keys.created_at, api_keys.revoked_at,
       api_keys.scopes, api_keys.expires_at, api_keys.last_used_at,
       tenants.status AS tenant_status
FROM api_keys
JOIN tenants ON tenants.id = api_keys.tenant_id
WHERE api_keys.key_hash = $1 AND api_keys.revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	Scopes       []string
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	TenantStatus string
}

// Joins tenants so the resolver gets the tenant's current status alongside
// the key in the same round trip (Task 2.1, ADR-015): gating needs no extra
// query. The join is safe against a dangling reference: api_keys_tenant_fk
// (migration 0011) guarantees every api_keys row's tenant_id has a tenants
// row. scopes, expires_at, and last_used_at (Task 2.2) are returned as-is:
// expiry and scope enforcement happen in the resolver and the transport
// middleware, not in this query.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RateLimitRpm,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.TenantStatus,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, tenant_id, name, rate_limit_rpm, created_at, revoked_at, scopes, expires_at, last_used_at
FROM api_keys
WHERE id = $1
`

type GetAPIKeyByIDRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	Scopes       []string
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

// Raw fetch by id, unfiltered by revoked_at: the admin surface (Task 2.2b)
// uses this to look up an existing key (including an already-revoked one) by
// id, for example to copy a key's tenant/name/scopes when rotating it. It
// does not join tenants: callers that need the tenant's current status look
// it up separately via GetTenant.
func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (GetAPIKeyByIDRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i GetAPIKeyByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RateLimitRpm,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (id, tenant_id, name, key_hash, rate_limit_rpm, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAPIKeyParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	KeyHash      string
	RateLimitRpm pgtype.Int4
	Scopes       []string
	ExpiresAt    pgtype.Timestamptz
}

// scopes and expires_at (Task 2.2b) are now written on insert: the admin
// surface (internal/admin) is what actually sets them to something other
// than the column default. Every pre-2.2b caller (cmd/server's demo and
// load-test key provisioning, and every repository test that predates
// scopes) still works unchanged, because the Go-level repository method
// defaults an empty Scopes slice to {read,post} before it ever reaches this
// query, the same default the api_keys.scopes column itself carries.
func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.RateLimitRpm,
		arg.Scopes,
		arg.ExpiresAt,
	)
	return err
}

const listAPIKeysByTenant = `-- name: ListAPIKeysByTenant :many
SELECT id, tenant_id, name, rate_limit_rpm, created_at, revoked_at, scopes, expires_at, last_used_at
FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at, id
`

type ListAPIKeysByTenantRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	Scopes       []string
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

// Every key for a tenant, oldest first, including revoked ones: the admin
// surface's list view (Task 2.2b) is meant to show a tenant's full key
// history, not just its live keys. Never selects key_hash: plaintext is
// shown once at issue/rotate time and is never recoverable afterward, and
// the hash itself has no business leaving the resolver's lookup path.
func (q *Queries) ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAPIKeysByTenantRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysByTenantRow
	for rows.Next() {
		var i ListAPIKeysByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.RateLimitRpm,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :execrows
UPDATE api_keys SET revoked_at = COALESCE(revoked_at, now()) WHERE id = $1
`

// COALESCE makes this idempotent: revoking an already-revoked key keeps its
// original revoked_at instead of bumping it, and still reports one row
// affected (not zero), so the admin service can tell "no such key" (0 rows)
// from "already revoked" (1 row, unchanged) without a separate lookup.
func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAPIKeyScopesByHash = `-- name: SetAPIKeyScopesByHash :exec
UPDATE api_keys SET scopes = $2 WHERE key_hash = $1
`

type SetAPIKeyScopesByHashParams struct {
	KeyHash string
	Scopes  []string
}

// Reconciles an already-existing key's scopes to exactly the given set, keyed
// by hash rather than id (ADR-019 follow-up, review fix): InsertAPIKey is
// insert-or-ignore on the unique key_hash, so a demo key row left over from a
// previous boot never has its scopes touched by a plain re-insert. cmd/server
// calls this right after provisioning the demo key, keyed by
// domain.HashAPIKey of its known plaintext, so the row's scopes always match
// demoKeyScopes(cfg.demoMode): it gains admin scope when demo mode turns on,
// and correctly loses it when a deployment flips out of demo mode. A hash
// with no matching row affects zero rows, which is fine: the INSERT that
// runs immediately before this in provisioning order creates it first.
func (q *Queries) SetAPIKeyScopesByHash(ctx context.Context, arg SetAPIKeyScopesByHashParams) error {
	_, err := q.db.Exec(ctx, setAPIKeyScopesByHash, arg.KeyHash, arg.Scopes)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = $2 WHERE id = $1
`

type TouchAPIKeyLastUsedParams struct {
	ID         uuid.UUID
	LastUsedAt pgtype.Timestamptz
}

// Updates last_used_at for a single key by id. Called best-effort and
// throttled from the auth resolver (Task 2.2): not every request, so this is
// not a write on the hot path of every authenticated call.
func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
