// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, tenant_id, name, rate_limit_rpm, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.RateLimitRpm,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (id, tenant_id, name, key_hash, rate_limit_rpm)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAPIKeyParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	KeyHash      string
	RateLimitRpm pgtype.Int4
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.RateLimitRpm,
	)
	return err
}
