// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, tenant_id, action, transaction_id, actor, before, after)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditLogParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.Action,
		arg.TransactionID,
		arg.Actor,
		arg.Before,
		arg.After,
	)
	return err
}

const listAuditByAccount = `-- name: ListAuditByAccount :many
SELECT audit_log.id, audit_log.tenant_id, audit_log.action, audit_log.transaction_id,
       audit_log.actor, audit_log.before, audit_log.after, audit_log.created_at
FROM audit_log
WHERE audit_log.tenant_id = $1
  AND audit_log.transaction_id IN (
    SELECT DISTINCT postings.transaction_id
    FROM postings
    WHERE postings.tenant_id = $1 AND postings.account_id = $2
  )
ORDER BY audit_log.created_at, audit_log.id
`

type ListAuditByAccountParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ListAuditByAccount(ctx context.Context, arg ListAuditByAccountParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByAccount, arg.TenantID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTransaction = `-- name: ListAuditByTransaction :many
SELECT id, tenant_id, action, transaction_id, actor, before, after, created_at
FROM audit_log
WHERE tenant_id = $1 AND transaction_id = $2
ORDER BY created_at, id
`

type ListAuditByTransactionParams struct {
	TenantID      uuid.UUID
	TransactionID uuid.UUID
}

func (q *Queries) ListAuditByTransaction(ctx context.Context, arg ListAuditByTransactionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTransaction, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
