// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_outbox.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const auditOutboxWatermark = `-- name: AuditOutboxWatermark :one
SELECT pg_snapshot_xmin(pg_current_snapshot())::text::bigint
`

// The oldest transaction id still in flight, cast the same way audit_outbox.txid
// is (xid8 has no direct cast to bigint). A row whose txid is strictly below
// this watermark is guaranteed committed and safe to chain (ADR-017,
// "Ordering: process only settled rows, in transaction-commit order").
func (q *Queries) AuditOutboxWatermark(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, auditOutboxWatermark)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingOutbox = `-- name: CountPendingOutbox :one
SELECT count(*) FROM audit_outbox
WHERE tenant_id = $1 AND processed_at IS NULL
`

// Unprocessed outbox rows for one tenant: the lag the verify endpoint reports
// alongside the chained head (ADR-017 section 5), so a caller can see whether
// the chain is current or behind.
func (q *Queries) CountPendingOutbox(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingOutbox, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditOutbox = `-- name: InsertAuditOutbox :exec
INSERT INTO audit_outbox (tenant_id, action, transaction_id, actor, before, after)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditOutboxParams struct {
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
}

// Writes one outbox row inside the caller's own transaction (ADR-017): the
// event is durable if and only if the surrounding post/convert transaction
// commits. occurred_at, txid, and created_at are all left to their column
// defaults (the database server's now() and pg_current_xact_id(), see
// migration 0015): no chain read, no hash computed, here.
func (q *Queries) InsertAuditOutbox(ctx context.Context, arg InsertAuditOutboxParams) error {
	_, err := q.db.Exec(ctx, insertAuditOutbox,
		arg.TenantID,
		arg.Action,
		arg.TransactionID,
		arg.Actor,
		arg.Before,
		arg.After,
	)
	return err
}

const markAuditOutboxProcessed = `-- name: MarkAuditOutboxProcessed :exec
UPDATE audit_outbox SET processed_at = now() WHERE id = $1
`

// Sets processed_at for one outbox row. The chainer calls this in the same
// transaction as the audit_log insert it produced, so a crash between the two
// is impossible: either both happen or neither does.
func (q *Queries) MarkAuditOutboxProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markAuditOutboxProcessed, id)
	return err
}

const scanUnprocessedAuditOutbox = `-- name: ScanUnprocessedAuditOutbox :many
SELECT id, tenant_id, action, transaction_id, actor, before, after, occurred_at, txid
FROM audit_outbox
WHERE processed_at IS NULL AND txid < $1
ORDER BY txid, id
LIMIT $2
`

type ScanUnprocessedAuditOutboxParams struct {
	Xmin       int64
	BatchLimit int32
}

type ScanUnprocessedAuditOutboxRow struct {
	ID            int64
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
	OccurredAt    time.Time
	Txid          int64
}

// The chainer's batch read: unprocessed rows whose inserting transaction is
// guaranteed settled (txid < the watermark passed in), oldest commit order
// first. Ordering by (txid, id) is the total order ADR-017 defines: it is
// stable because txid is not reused and id is a bigserial tiebreaker for the
// (rare) case of equal txid.
func (q *Queries) ScanUnprocessedAuditOutbox(ctx context.Context, arg ScanUnprocessedAuditOutboxParams) ([]ScanUnprocessedAuditOutboxRow, error) {
	rows, err := q.db.Query(ctx, scanUnprocessedAuditOutbox, arg.Xmin, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanUnprocessedAuditOutboxRow
	for rows.Next() {
		var i ScanUnprocessedAuditOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.OccurredAt,
			&i.Txid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
