// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLastAuditHash = `-- name: GetLastAuditHash :one
SELECT row_hash FROM audit_log
WHERE tenant_id = $1
ORDER BY id DESC
LIMIT 1
`

// The tenant's most recent row_hash, used to extend the per-tenant hash chain.
// Ordered by id, not created_at (ADR-017): id is a UUIDv7 assigned by the
// single chainer at chain-insertion time, via a generator guaranteed to
// return strictly increasing values across successive calls in that one
// process (see google/uuid's NewV7), so it is the true chain order. created_at
// is copied from the ORIGINATING event's post time (audit_outbox.occurred_at),
// which under concurrent posts across many transactions is NOT guaranteed to
// be monotonic with the order those transactions actually commit in (a
// transaction that starts later can commit first); ordering by created_at
// would occasionally return the wrong "latest" row and corrupt the chain. A
// fresh tenant (or one with no rows yet) surfaces as pgx.ErrNoRows; the
// caller treats that as the chain's genesis (domain.AuditGenesisHash).
func (q *Queries) GetLastAuditHash(ctx context.Context, tenantID uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLastAuditHash, tenantID)
	var row_hash pgtype.Text
	err := row.Scan(&row_hash)
	return row_hash, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (id, tenant_id, action, transaction_id, actor, before, after, created_at, prev_hash, row_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditLogParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
	CreatedAt     time.Time
	PrevHash      pgtype.Text
	RowHash       pgtype.Text
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.TenantID,
		arg.Action,
		arg.TransactionID,
		arg.Actor,
		arg.Before,
		arg.After,
		arg.CreatedAt,
		arg.PrevHash,
		arg.RowHash,
	)
	return err
}

const listAuditByAccount = `-- name: ListAuditByAccount :many
SELECT audit_log.id, audit_log.tenant_id, audit_log.action, audit_log.transaction_id,
       audit_log.actor, audit_log.before, audit_log.after, audit_log.created_at,
       audit_log.prev_hash, audit_log.row_hash
FROM audit_log
WHERE audit_log.tenant_id = $1
  AND audit_log.transaction_id IN (
    SELECT DISTINCT postings.transaction_id
    FROM postings
    WHERE postings.tenant_id = $1 AND postings.account_id = $2
  )
  AND audit_log.id < $3
ORDER BY audit_log.id DESC
LIMIT $4
`

type ListAuditByAccountParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
	AfterID   uuid.UUID
	PageLimit int32
}

// Keyset page of audit rows for every transaction with a posting touching the
// account, newest first. after_id is the keyset position: pass the max uuid
// for the first page. Ordered and paged by id alone, not (created_at, id):
// see GetLastAuditHash's comment (ADR-017) for why id, assigned by the
// chainer in true chain-insertion order, is what must drive ordering here,
// not created_at (copied from the original event's post time, which is not
// guaranteed monotonic with commit order under concurrent posts).
func (q *Queries) ListAuditByAccount(ctx context.Context, arg ListAuditByAccountParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByAccount,
		arg.TenantID,
		arg.AccountID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTransaction = `-- name: ListAuditByTransaction :many
SELECT id, tenant_id, action, transaction_id, actor, before, after, created_at, prev_hash, row_hash
FROM audit_log
WHERE tenant_id = $1 AND transaction_id = $2
ORDER BY id
`

type ListAuditByTransactionParams struct {
	TenantID      uuid.UUID
	TransactionID uuid.UUID
}

// Ordered by id, not created_at: see GetLastAuditHash's comment (ADR-017) for
// why id is the chain-consistent order and created_at is not.
func (q *Queries) ListAuditByTransaction(ctx context.Context, arg ListAuditByTransactionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTransaction, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditForVerify = `-- name: ListAuditForVerify :many
SELECT id, tenant_id, action, transaction_id, actor, before, after, created_at, prev_hash, row_hash
FROM audit_log
WHERE tenant_id = $1
ORDER BY id
`

// Every audit row for the tenant, in true chain order: the full walk used to
// recompute and check the tamper-evident hash chain end to end. Ordered by
// id, not created_at: see GetLastAuditHash's comment (ADR-017) for why.
func (q *Queries) ListAuditForVerify(ctx context.Context, tenantID uuid.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditForVerify, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.Actor,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
