// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: disputes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDispute = `-- name: CreateDispute :exec
INSERT INTO disputes (id, tenant_id, transaction_id, reason)
VALUES ($1, $2, $3, $4)
`

type CreateDisputeParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	Reason        string
}

// Task 6.3, audit A9.2: status is NOT inserted explicitly (the column
// default 'open' applies), the same convention CreateAccount leaves status
// to its own column default for.
func (q *Queries) CreateDispute(ctx context.Context, arg CreateDisputeParams) error {
	_, err := q.db.Exec(ctx, createDispute,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.Reason,
	)
	return err
}

const getDispute = `-- name: GetDispute :one
SELECT id, tenant_id, transaction_id, status, reason, resolution_transaction_id, created_at, resolved_at
FROM disputes
WHERE tenant_id = $1 AND id = $2
`

type GetDisputeParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetDispute(ctx context.Context, arg GetDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, getDispute, arg.TenantID, arg.ID)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionID,
		&i.Status,
		&i.Reason,
		&i.ResolutionTransactionID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listDisputes = `-- name: ListDisputes :many
SELECT id, tenant_id, transaction_id, status, reason, resolution_transaction_id, created_at, resolved_at
FROM disputes
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND (created_at < $3
       OR (created_at = $3 AND id < $4))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListDisputesParams struct {
	TenantID       uuid.UUID
	Status         pgtype.Text
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

// Filtered, keyset-paged list of a tenant's disputes, newest first (Task
// 6.3, audit A9.2). status is an optional filter via sqlc.narg: NULL
// disables it (every status is returned). Keyset paged by (created_at, id)
// descending, the identical cursor shape ListTransactions and
// AccountStatement already use.
func (q *Queries) ListDisputes(ctx context.Context, arg ListDisputesParams) ([]Dispute, error) {
	rows, err := q.db.Query(ctx, listDisputes,
		arg.TenantID,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Dispute
	for rows.Next() {
		var i Dispute
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.Status,
			&i.Reason,
			&i.ResolutionTransactionID,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveDispute = `-- name: ResolveDispute :one
UPDATE disputes
SET status = $3, resolution_transaction_id = $4, resolved_at = now()
WHERE tenant_id = $1 AND id = $2 AND status = 'open'
RETURNING id, tenant_id, transaction_id, status, reason, resolution_transaction_id, created_at, resolved_at
`

type ResolveDisputeParams struct {
	TenantID                uuid.UUID
	ID                      uuid.UUID
	Status                  string
	ResolutionTransactionID pgtype.UUID
}

// Task 6.3, audit A9.2: the guarded transition out of 'open'. The WHERE
// status = 'open' clause is what makes resolving an already-resolved (or
// concurrently-being-resolved) dispute return zero rows rather than
// silently overwriting a prior resolution: the caller
// (postgres.Repository.ResolveDispute) treats a zero-row result as
// domain.ErrDisputeAlreadyResolved.
func (q *Queries) ResolveDispute(ctx context.Context, arg ResolveDisputeParams) (Dispute, error) {
	row := q.db.QueryRow(ctx, resolveDispute,
		arg.TenantID,
		arg.ID,
		arg.Status,
		arg.ResolutionTransactionID,
	)
	var i Dispute
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TransactionID,
		&i.Status,
		&i.Reason,
		&i.ResolutionTransactionID,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
