// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_markup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const globalFXMarkupDefault = `-- name: GlobalFXMarkupDefault :one
SELECT id, tenant_id, default_spread_bps, source, effective_at, created_at
FROM fx_markup_defaults
WHERE tenant_id IS NULL AND effective_at <= now()
ORDER BY effective_at DESC, id DESC
LIMIT 1
`

// The current global default only (tenant_id IS NULL), so the console can
// show it distinctly from a tenant override.
func (q *Queries) GlobalFXMarkupDefault(ctx context.Context) (FxMarkupDefault, error) {
	row := q.db.QueryRow(ctx, globalFXMarkupDefault)
	var i FxMarkupDefault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DefaultSpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertFXMarkupDefault = `-- name: InsertFXMarkupDefault :one
INSERT INTO fx_markup_defaults (tenant_id, default_spread_bps, source, effective_at)
VALUES ($1, $3::integer, $2, COALESCE($4::timestamptz, now()))
RETURNING id, tenant_id, default_spread_bps, source, effective_at, created_at
`

type InsertFXMarkupDefaultParams struct {
	TenantID         pgtype.UUID
	Source           string
	DefaultSpreadBps pgtype.Int4
	EffectiveAt      pgtype.Timestamptz
}

// fx_markup_defaults is append-only (ADR-020): a new default is a new row.
// tenant_id NULL is the global default, a non-NULL tenant_id is that tenant's
// override. effective_at is server-stamped via COALESCE(narg, now()) for the
// same clock-skew reason InsertFXRate stamps server-side. default_spread_bps
// is a nullable narg: a NULL value inserts a cleared row (the tenant follows
// the global default again), matching the nullable fx_rates.spread_bps
// pattern.
func (q *Queries) InsertFXMarkupDefault(ctx context.Context, arg InsertFXMarkupDefaultParams) (FxMarkupDefault, error) {
	row := q.db.QueryRow(ctx, insertFXMarkupDefault,
		arg.TenantID,
		arg.Source,
		arg.DefaultSpreadBps,
		arg.EffectiveAt,
	)
	var i FxMarkupDefault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DefaultSpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const tenantFXMarkupDefault = `-- name: TenantFXMarkupDefault :one
SELECT id, tenant_id, default_spread_bps, source, effective_at, created_at
FROM fx_markup_defaults
WHERE tenant_id = $1 AND effective_at <= now()
ORDER BY effective_at DESC, id DESC
LIMIT 1
`

// The current default owned by exactly this tenant (no global fallback), so
// the console can show whether the tenant has its own override at all.
func (q *Queries) TenantFXMarkupDefault(ctx context.Context, tenantID pgtype.UUID) (FxMarkupDefault, error) {
	row := q.db.QueryRow(ctx, tenantFXMarkupDefault, tenantID)
	var i FxMarkupDefault
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DefaultSpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}
