// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_rates.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const currentFXRate = `-- name: CurrentFXRate :one
SELECT id, base, quote, mid_rate_e8, spread_bps, source, effective_at, created_at, tenant_id
FROM fx_rates
WHERE base = $2 AND quote = $3
  AND (tenant_id = $1 OR tenant_id IS NULL)
  AND effective_at <= now()
ORDER BY (tenant_id IS NULL), effective_at DESC, id DESC
LIMIT 1
`

type CurrentFXRateParams struct {
	TenantID pgtype.UUID
	Base     string
	Quote    string
}

// The latest quote for (base, quote) at or before now, preferring a
// tenant-specific row over the global default (Task 2.4, audit A3.3):
// tenant_id = $1 matches the tenant's own rows, and tenant_id IS NULL always
// matches the global default, so a tenant with no row of its own still
// resolves the global one. ORDER BY (tenant_id IS NULL) sorts a tenant-owned
// row (false, i.e. 0) ahead of a global row (true, i.e. 1), so when both
// exist the tenant's own wins regardless of which is more recently
// effective; effective_at DESC, id DESC is then the same "latest, ties
// broken by insertion order" tiebreak CurrentFXRate always used, applied
// within whichever tier (tenant-owned or global) won.
func (q *Queries) CurrentFXRate(ctx context.Context, arg CurrentFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, currentFXRate, arg.TenantID, arg.Base, arg.Quote)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.MidRateE8,
		&i.SpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const insertFXRate = `-- name: InsertFXRate :one
INSERT INTO fx_rates (tenant_id, base, quote, mid_rate_e8, spread_bps, source, effective_at)
VALUES ($1, $2, $3, $4, $6::integer, $5, COALESCE($7::timestamptz, now()))
RETURNING id, base, quote, mid_rate_e8, spread_bps, source, effective_at, created_at, tenant_id
`

type InsertFXRateParams struct {
	TenantID    pgtype.UUID
	Base        string
	Quote       string
	MidRateE8   int64
	Source      string
	SpreadBps   pgtype.Int4
	EffectiveAt pgtype.Timestamptz
}

// fx_rates is append-only (ADR-014): a new quote is a new row, never an
// update, so every rate ever applied to a transaction stays reconstructible.
// tenant_id NULL makes this the global default rate for the pair; a non-NULL
// tenant_id makes it that tenant's own rate (Task 2.4, audit A3.3), resolved
// ahead of the global default by CurrentFXRate below.
//
// effective_at is a nullable named param (sqlc.narg): when the caller omits
// an explicit effective_at, COALESCE falls through to the DATABASE SERVER's
// now(), never the calling process's clock. Stamping an "immediate" rate
// with the caller's clock is what caused a real clock-skew bug (Task 2.4
// remediation): CurrentFXRate below gates on "effective_at <= now()" using
// the server's clock too, so if the caller's clock ran even slightly ahead,
// a just-inserted row was transiently invisible and the query silently fell
// through to the global default. Passing NULL here (rather than the CLI
// host's time.Now()) makes the two clocks the same clock for the common,
// unscheduled case; an explicit future effective_at (a scheduled rate) is
// unaffected, since the caller still supplies it directly.
func (q *Queries) InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, insertFXRate,
		arg.TenantID,
		arg.Base,
		arg.Quote,
		arg.MidRateE8,
		arg.Source,
		arg.SpreadBps,
		arg.EffectiveAt,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.MidRateE8,
		&i.SpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
		&i.TenantID,
	)
	return i, err
}

const listCurrentFXRates = `-- name: ListCurrentFXRates :many
SELECT DISTINCT ON (base, quote)
    id, tenant_id, base, quote, mid_rate_e8, spread_bps, source, effective_at, created_at
FROM fx_rates
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND effective_at <= now()
ORDER BY base, quote, (tenant_id IS NULL), effective_at DESC, id DESC
`

type ListCurrentFXRatesRow struct {
	ID          int64
	TenantID    pgtype.UUID
	Base        string
	Quote       string
	MidRateE8   int64
	SpreadBps   pgtype.Int4
	Source      string
	EffectiveAt time.Time
	CreatedAt   time.Time
}

// The current effective row per (base, quote) for a tenant plus the global
// defaults: DISTINCT ON collapses each pair to one row, and the ORDER BY puts
// a tenant-owned row (tenant_id IS NULL = false, sorts first) ahead of a
// global row, then latest effective, matching CurrentFXRate's precedence.
// Pass tenant_id NULL to list globals only (tenant_id = NULL is never true, so
// only the tenant_id IS NULL rows match).
func (q *Queries) ListCurrentFXRates(ctx context.Context, tenantID pgtype.UUID) ([]ListCurrentFXRatesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFXRates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentFXRatesRow
	for rows.Next() {
		var i ListCurrentFXRatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Base,
			&i.Quote,
			&i.MidRateE8,
			&i.SpreadBps,
			&i.Source,
			&i.EffectiveAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
