// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_rates.sql

package sqlc

import (
	"context"
	"time"
)

const currentFXRate = `-- name: CurrentFXRate :one
SELECT id, base, quote, mid_rate_e8, spread_bps, source, effective_at, created_at
FROM fx_rates
WHERE base = $1 AND quote = $2 AND effective_at <= now()
ORDER BY effective_at DESC, id DESC
LIMIT 1
`

type CurrentFXRateParams struct {
	Base  string
	Quote string
}

// The latest quote for (base, quote) at or before now. id DESC is the
// deterministic tiebreaker when two rows share the same effective_at (for
// example a re-seed within the same second), so "current" always resolves to
// exactly one row.
func (q *Queries) CurrentFXRate(ctx context.Context, arg CurrentFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, currentFXRate, arg.Base, arg.Quote)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.MidRateE8,
		&i.SpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertFXRate = `-- name: InsertFXRate :one
INSERT INTO fx_rates (base, quote, mid_rate_e8, spread_bps, source, effective_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, base, quote, mid_rate_e8, spread_bps, source, effective_at, created_at
`

type InsertFXRateParams struct {
	Base        string
	Quote       string
	MidRateE8   int64
	SpreadBps   int32
	Source      string
	EffectiveAt time.Time
}

// fx_rates is append-only (ADR-014): a new quote is a new row, never an
// update, so every rate ever applied to a transaction stays reconstructible.
func (q *Queries) InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, insertFXRate,
		arg.Base,
		arg.Quote,
		arg.MidRateE8,
		arg.SpreadBps,
		arg.Source,
		arg.EffectiveAt,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.Base,
		&i.Quote,
		&i.MidRateE8,
		&i.SpreadBps,
		&i.Source,
		&i.EffectiveAt,
		&i.CreatedAt,
	)
	return i, err
}
