// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, idempotency_key, fingerprint, fingerprint_scheme, transaction_id, created_at
FROM idempotency_keys
WHERE tenant_id = $1 AND idempotency_key = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

type GetIdempotencyKeyRow struct {
	TenantID          uuid.UUID
	IdempotencyKey    string
	Fingerprint       string
	FingerprintScheme string
	TransactionID     uuid.UUID
	CreatedAt         time.Time
}

// An expired row is treated as absent (Task 4.5, audit A1.4): the "AND
// expires_at > now()" filter is what makes a key whose replay window has
// passed behave exactly like a key that was never written, from the caller's
// point of view, whether or not the background sweep has physically deleted
// the row yet.
func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintScheme,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :one
INSERT INTO idempotency_keys (tenant_id, idempotency_key, fingerprint, fingerprint_scheme, transaction_id, expires_at)
VALUES ($1, $2, $3, $4, $5, now() + ($6::float8 * interval '1 second'))
ON CONFLICT (tenant_id, idempotency_key) DO UPDATE
    SET fingerprint        = EXCLUDED.fingerprint,
        fingerprint_scheme = EXCLUDED.fingerprint_scheme,
        transaction_id     = EXCLUDED.transaction_id,
        created_at         = now(),
        expires_at         = EXCLUDED.expires_at
    WHERE idempotency_keys.expires_at <= now()
RETURNING tenant_id
`

type InsertIdempotencyKeyParams struct {
	TenantID          uuid.UUID
	IdempotencyKey    string
	Fingerprint       string
	FingerprintScheme string
	TransactionID     uuid.UUID
	TtlSeconds        float64
}

// Inserts a fresh idempotency key with a server-computed expires_at (now() +
// ttl_seconds, never the calling process's clock: Task 4.5, audit A1.4,
// consistent with fx_rates.effective_at's own server-side stamping).
//
// ON CONFLICT upserts rather than plain-inserts because a row for
// (tenant_id, idempotency_key) can already be present and EXPIRED: the
// lookup path (GetIdempotencyKey) treats an expired row as absent, so the
// caller proceeds to post a brand-new transaction and lands here again with
// the same key. Without the upsert that would hit the primary key and be
// misread as a genuine duplicate (replaying a stale, no-longer-relevant
// transaction). The "WHERE idempotency_keys.expires_at <= now()" guard on
// the DO UPDATE means the replace only happens when the existing row has, in
// fact, expired; a conflict against a still-live row leaves it untouched and
// the update affects zero rows, so RETURNING yields no row and the caller
// (postgres.txRepo.InsertIdempotencyKey) maps pgx.ErrNoRows to
// domain.ErrDuplicateIdempotencyKey exactly as a plain unique-violation used
// to, preserving replay-on-duplicate for the still-live case.
func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertIdempotencyKey,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.FingerprintScheme,
		arg.TransactionID,
		arg.TtlSeconds,
	)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const sweepExpiredIdempotencyKeysBatch = `-- name: SweepExpiredIdempotencyKeysBatch :execrows
DELETE FROM idempotency_keys
WHERE ctid IN (
    SELECT ctid FROM idempotency_keys
    WHERE expires_at < now()
    LIMIT $1::int
)
`

// Deletes up to batch_size idempotency keys whose replay window has passed,
// across all tenants (Task 4.5, audit A1.4; batched per the follow-up
// review: a plain "DELETE ... WHERE expires_at < now()" has no bound, so a
// large backlog could delete an unbounded number of rows in one statement
// and contend with live posts). The ctid subquery caps each statement's own
// row scan/lock footprint to batch_size rows instead of the whole table.
// Not tenant-scoped and not run inside RunInTx: it is a plain maintenance
// statement. The Go caller (postgres.Repository.SweepExpiredIdempotencyKeys)
// loops this query in batches until a call deletes 0 rows (or a max
// iteration guard trips), summing the deleted count for the sweep log line.
func (q *Queries) SweepExpiredIdempotencyKeysBatch(ctx context.Context, batchSize int32) (int64, error) {
	result, err := q.db.Exec(ctx, sweepExpiredIdempotencyKeysBatch, batchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
