// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT tenant_id, idempotency_key, fingerprint, fingerprint_scheme, transaction_id, created_at
FROM idempotency_keys
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

type GetIdempotencyKeyRow struct {
	TenantID          uuid.UUID
	IdempotencyKey    string
	Fingerprint       string
	FingerprintScheme string
	TransactionID     uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintScheme,
		&i.TransactionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (tenant_id, idempotency_key, fingerprint, fingerprint_scheme, transaction_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertIdempotencyKeyParams struct {
	TenantID          uuid.UUID
	IdempotencyKey    string
	Fingerprint       string
	FingerprintScheme string
	TransactionID     uuid.UUID
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.FingerprintScheme,
		arg.TransactionID,
	)
	return err
}
