// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	Name           string
	Type           string
	Currency       string
	CreatedAt      time.Time
	IsSystem       bool
	Status         string
	MinBalance     pgtype.Int8
	PartyReference pgtype.Text
	PartyType      pgtype.Text
}

type ApiKey struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	KeyHash      string
	RateLimitRpm pgtype.Int4
	CreatedAt    time.Time
	RevokedAt    pgtype.Timestamptz
	Scopes       []string
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
}

type AuditAnchor struct {
	ID        int64
	TenantID  uuid.UUID
	ChainSeq  int64
	RowHash   string
	CreatedAt time.Time
}

type AuditLog struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
	CreatedAt     time.Time
	PrevHash      pgtype.Text
	RowHash       pgtype.Text
	ChainSeq      int64
	OutboxID      pgtype.Int8
}

type AuditOutbox struct {
	ID            int64
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
	OccurredAt    time.Time
	Txid          int64
	CreatedAt     time.Time
	ProcessedAt   pgtype.Timestamptz
}

type CryptoKey struct {
	TenantID   uuid.UUID
	WrappedDek []byte
	CreatedAt  time.Time
	ShreddedAt pgtype.Timestamptz
	Version    int32
}

type Dispute struct {
	ID                      uuid.UUID
	TenantID                uuid.UUID
	TransactionID           uuid.UUID
	Status                  string
	Reason                  string
	ResolutionTransactionID pgtype.UUID
	CreatedAt               time.Time
	ResolvedAt              pgtype.Timestamptz
}

type FxMarkupDefault struct {
	ID               int64
	TenantID         pgtype.UUID
	DefaultSpreadBps pgtype.Int4
	Source           string
	EffectiveAt      time.Time
	CreatedAt        time.Time
}

type FxRate struct {
	ID          int64
	Base        string
	Quote       string
	MidRateE8   int64
	SpreadBps   pgtype.Int4
	Source      string
	EffectiveAt time.Time
	CreatedAt   time.Time
	TenantID    pgtype.UUID
}

type IdempotencyKey struct {
	TenantID          uuid.UUID
	IdempotencyKey    string
	Fingerprint       string
	TransactionID     uuid.UUID
	CreatedAt         time.Time
	FingerprintScheme string
	ExpiresAt         time.Time
}

type Posting struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	CreatedAt     time.Time
	Description   string
	Currency      string
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	Status    string
	Settings  []byte
	CreatedAt time.Time
}

type Transaction struct {
	ID                    uuid.UUID
	TenantID              uuid.UUID
	CreatedAt             time.Time
	FxSourceAmount        pgtype.Int8
	FxConvertedAmount     pgtype.Int8
	FxMidRateE8           pgtype.Int8
	FxSpreadBps           pgtype.Int4
	FxAppliedE8           pgtype.Int8
	FxRateSource          pgtype.Text
	FxEffectiveAt         pgtype.Timestamptz
	FxRateID              pgtype.Int8
	ReversesTransactionID pgtype.UUID
	Reference             pgtype.Text
	EffectiveAt           pgtype.Timestamptz
}

type WebhookDelivery struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SubscriptionID uuid.UUID
	AuditChainSeq  int64
	EventType      string
	Payload        []byte
	Status         string
	Attempts       int32
	NextAttemptAt  time.Time
	LastError      pgtype.Text
	CreatedAt      time.Time
	DeliveredAt    pgtype.Timestamptz
}

type WebhookFanoutCursor struct {
	ID           bool
	LastChainSeq int64
}

type WebhookSubscription struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Secret     string
	EventTypes []string
	Active     bool
	CreatedAt  time.Time
}
