// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Type      string
	Currency  string
	CreatedAt time.Time
}

type Posting struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	CreatedAt     time.Time
}

type Transaction struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Currency  string
	CreatedAt time.Time
}
