// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Account struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	Type      string
	Currency  string
	CreatedAt time.Time
}

type AuditLog struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	Action        string
	TransactionID uuid.UUID
	Actor         string
	Before        []byte
	After         []byte
	CreatedAt     time.Time
}

type IdempotencyKey struct {
	TenantID       uuid.UUID
	IdempotencyKey string
	Fingerprint    string
	TransactionID  uuid.UUID
	CreatedAt      time.Time
}

type Posting struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	CreatedAt     time.Time
	Description   string
}

type Transaction struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Currency  string
	CreatedAt time.Time
}
