// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPendingForUpdate = `-- name: GetPendingForUpdate :one
SELECT id, tenant_id, kind, payload, status, threshold_ccy, threshold_amt, created_by, created_at, decided_by, decided_at, reason, transaction_id
FROM pending_transactions
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type GetPendingForUpdateParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Task 4 (ADR-025): the row-locking read a decision (approve/reject/cancel)
// takes before transitioning a pending, so two racing decisions cannot both
// win; the loser's transaction blocks on this lock until the winner commits
// or rolls back, then re-reads the now-terminal row. Called only from
// inside RunInTx (via the Tx port), never as a standalone read.
func (q *Queries) GetPendingForUpdate(ctx context.Context, arg GetPendingForUpdateParams) (PendingTransaction, error) {
	row := q.db.QueryRow(ctx, getPendingForUpdate, arg.TenantID, arg.ID)
	var i PendingTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.ThresholdCcy,
		&i.ThresholdAmt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.TransactionID,
	)
	return i, err
}

const getPendingTransaction = `-- name: GetPendingTransaction :one
SELECT id, tenant_id, kind, payload, status, threshold_ccy, threshold_amt, created_by, created_at, decided_by, decided_at, reason, transaction_id
FROM pending_transactions
WHERE tenant_id = $1 AND id = $2
`

type GetPendingTransactionParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetPendingTransaction(ctx context.Context, arg GetPendingTransactionParams) (PendingTransaction, error) {
	row := q.db.QueryRow(ctx, getPendingTransaction, arg.TenantID, arg.ID)
	var i PendingTransaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.ThresholdCcy,
		&i.ThresholdAmt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
		&i.TransactionID,
	)
	return i, err
}

const insertPendingTransaction = `-- name: InsertPendingTransaction :exec
INSERT INTO pending_transactions (id, tenant_id, kind, payload, threshold_ccy, threshold_amt, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPendingTransactionParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Kind         string
	Payload      []byte
	ThresholdCcy string
	ThresholdAmt int64
	CreatedBy    string
}

// Task 4 (ADR-025): status is NOT inserted explicitly (the column default
// 'pending' applies), the same convention CreateDispute leaves status to its
// own column default for.
func (q *Queries) InsertPendingTransaction(ctx context.Context, arg InsertPendingTransactionParams) error {
	_, err := q.db.Exec(ctx, insertPendingTransaction,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.Payload,
		arg.ThresholdCcy,
		arg.ThresholdAmt,
		arg.CreatedBy,
	)
	return err
}

const listPendingTransactions = `-- name: ListPendingTransactions :many
SELECT id, tenant_id, kind, payload, status, threshold_ccy, threshold_amt, created_by, created_at, decided_by, decided_at, reason, transaction_id
FROM pending_transactions
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND (created_at < $3
       OR (created_at = $3 AND id < $4))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListPendingTransactionsParams struct {
	TenantID       uuid.UUID
	Status         pgtype.Text
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

// Filtered, keyset-paged list of a tenant's pendings, newest first (Task 4,
// ADR-025). status is an optional filter via sqlc.narg: NULL disables it
// (every status is returned). Keyset paged by (created_at, id) descending,
// the identical cursor shape ListDisputes already uses.
func (q *Queries) ListPendingTransactions(ctx context.Context, arg ListPendingTransactionsParams) ([]PendingTransaction, error) {
	rows, err := q.db.Query(ctx, listPendingTransactions,
		arg.TenantID,
		arg.Status,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingTransaction
	for rows.Next() {
		var i PendingTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.ThresholdCcy,
			&i.ThresholdAmt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingApprovedForTransaction = `-- name: PendingApprovedForTransaction :one
SELECT EXISTS(
    SELECT 1 FROM pending_transactions
    WHERE tenant_id = $1
      AND transaction_id = $2
      AND status = 'approved'
) AS exists
`

type PendingApprovedForTransactionParams struct {
	TenantID      uuid.UUID
	TransactionID pgtype.UUID
}

// Task 6 (ADR-025): the reverse-of-approved exemption's read. True only when
// some pending transaction's decision produced transaction_id AND that
// decision was an approval (a rejected or cancelled pending never sets
// transaction_id at all, per the transaction_id IS NULL OR status =
// 'approved' check in migration 0035, so the status filter here is mostly
// belt-and-suspenders). TransactionService.ReverseTransaction calls this
// before gating a reversal, never from inside RunInTx.
func (q *Queries) PendingApprovedForTransaction(ctx context.Context, arg PendingApprovedForTransactionParams) (bool, error) {
	row := q.db.QueryRow(ctx, pendingApprovedForTransaction, arg.TenantID, arg.TransactionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const sweepExpiredPending = `-- name: SweepExpiredPending :many
UPDATE pending_transactions
SET status = 'expired', decided_at = now(), decided_by = 'system'
WHERE status = 'pending'
  AND created_at < now() - ($1::float8 * interval '1 second')
RETURNING id, tenant_id, kind, payload, status, threshold_ccy, threshold_amt, created_by, created_at, decided_by, decided_at, reason, transaction_id
`

// Task 4 (ADR-025): the TTL sweep, mirroring
// SweepExpiredIdempotencyKeysBatch's role for idempotency keys. Runs
// outside any tenant's RunInTx (a background goroutine with no tenant GUC
// set, so the RLS policy's allow-when-unset branch lets it see every
// tenant), on an interval, moving every still-pending row older than
// older_than_seconds to 'expired' and decided_by 'system'. RETURNING the
// full rows lets the caller emit one approval.expired lifecycle event per
// row expired, without a second read. older_than_seconds is a float8 of
// seconds, not a Postgres interval literal, the same
// server-clock-independent-duration convention InsertIdempotencyKey's
// ttl_seconds already uses.
func (q *Queries) SweepExpiredPending(ctx context.Context, olderThanSeconds float64) ([]PendingTransaction, error) {
	rows, err := q.db.Query(ctx, sweepExpiredPending, olderThanSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingTransaction
	for rows.Next() {
		var i PendingTransaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.ThresholdCcy,
			&i.ThresholdAmt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePendingStatus = `-- name: UpdatePendingStatus :exec
UPDATE pending_transactions
SET status = $1, decided_by = $2, decided_at = now(),
    reason = $3, transaction_id = $4
WHERE tenant_id = $5 AND id = $6
`

type UpdatePendingStatusParams struct {
	Status        string
	DecidedBy     pgtype.Text
	Reason        pgtype.Text
	TransactionID pgtype.UUID
	TenantID      uuid.UUID
	ID            uuid.UUID
}

// Task 4 (ADR-025): the decision write. Always called after
// GetPendingForUpdate has already locked and validated the row within the
// same surrounding transaction, so this is a plain unconditional update, not
// a guarded one the way ResolveDispute's UPDATE ... WHERE status = 'open'
// is: the row lock is what prevents a second concurrent decision here, not
// a WHERE clause on this statement.
func (q *Queries) UpdatePendingStatus(ctx context.Context, arg UpdatePendingStatusParams) error {
	_, err := q.db.Exec(ctx, updatePendingStatus,
		arg.Status,
		arg.DecidedBy,
		arg.Reason,
		arg.TransactionID,
		arg.TenantID,
		arg.ID,
	)
	return err
}
