// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const accountBalance = `-- name: AccountBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM postings
WHERE tenant_id = $1 AND account_id = $2
`

type AccountBalanceParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountBalance, arg.TenantID, arg.AccountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const createPosting = `-- name: CreatePosting :exec
INSERT INTO postings (id, tenant_id, transaction_id, account_id, amount)
VALUES ($1, $2, $3, $4, $5)
`

type CreatePostingParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) error {
	_, err := q.db.Exec(ctx, createPosting,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
	)
	return err
}

const listPostingsByTransaction = `-- name: ListPostingsByTransaction :many
SELECT id, tenant_id, transaction_id, account_id, amount, created_at
FROM postings
WHERE tenant_id = $1 AND transaction_id = $2
ORDER BY created_at, id
`

type ListPostingsByTransactionParams struct {
	TenantID      uuid.UUID
	TransactionID uuid.UUID
}

func (q *Queries) ListPostingsByTransaction(ctx context.Context, arg ListPostingsByTransactionParams) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostingsByTransaction, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
