// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: postings.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const accountBalance = `-- name: AccountBalance :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM postings
WHERE tenant_id = $1 AND account_id = $2
`

type AccountBalanceParams struct {
	TenantID  uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error) {
	row := q.db.QueryRow(ctx, accountBalance, arg.TenantID, arg.AccountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const accountStatement = `-- name: AccountStatement :many
WITH entries AS (
    SELECT
        id,
        transaction_id,
        amount,
        description,
        created_at,
        (SUM(amount) OVER (ORDER BY created_at, id))::bigint AS running_balance
    FROM postings
    WHERE tenant_id = $1 AND account_id = $2
)
SELECT id, transaction_id, amount, running_balance, description, created_at
FROM entries
WHERE created_at < $3
   OR (created_at = $3 AND id < $4)
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type AccountStatementParams struct {
	TenantID       uuid.UUID
	AccountID      uuid.UUID
	AfterCreatedAt time.Time
	AfterID        uuid.UUID
	PageLimit      int32
}

type AccountStatementRow struct {
	ID             uuid.UUID
	TransactionID  uuid.UUID
	Amount         int64
	RunningBalance int64
	Description    string
	CreatedAt      time.Time
}

// Postings affecting an account, newest first, each with the running balance as
// of that posting. The running balance is a window SUM over the account's full
// posting history (the CTE); the keyset filter and limit then return one page.
// after_created_at / after_id are the keyset position: pass a far-future
// timestamp and the max uuid for the first page.
func (q *Queries) AccountStatement(ctx context.Context, arg AccountStatementParams) ([]AccountStatementRow, error) {
	rows, err := q.db.Query(ctx, accountStatement,
		arg.TenantID,
		arg.AccountID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountStatementRow
	for rows.Next() {
		var i AccountStatementRow
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.Amount,
			&i.RunningBalance,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPosting = `-- name: CreatePosting :exec
INSERT INTO postings (id, tenant_id, transaction_id, account_id, amount, description)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePostingParams struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	Description   string
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) error {
	_, err := q.db.Exec(ctx, createPosting,
		arg.ID,
		arg.TenantID,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.Description,
	)
	return err
}

const listPostingsByTransaction = `-- name: ListPostingsByTransaction :many
SELECT id, tenant_id, transaction_id, account_id, amount, description, created_at
FROM postings
WHERE tenant_id = $1 AND transaction_id = $2
ORDER BY created_at, id
`

type ListPostingsByTransactionParams struct {
	TenantID      uuid.UUID
	TransactionID uuid.UUID
}

type ListPostingsByTransactionRow struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        int64
	Description   string
	CreatedAt     time.Time
}

func (q *Queries) ListPostingsByTransaction(ctx context.Context, arg ListPostingsByTransactionParams) ([]ListPostingsByTransactionRow, error) {
	rows, err := q.db.Query(ctx, listPostingsByTransaction, arg.TenantID, arg.TransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostingsByTransactionRow
	for rows.Next() {
		var i ListPostingsByTransactionRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
