// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AccountBalance(ctx context.Context, arg AccountBalanceParams) (int64, error)
	// Postings affecting an account, newest first, each with the running balance as
	// of that posting. The running balance is a window SUM over the account's full
	// posting history (the CTE); the keyset filter and limit then return one page.
	// after_created_at / after_id are the keyset position: pass a far-future
	// timestamp and the max uuid for the first page.
	AccountStatement(ctx context.Context, arg AccountStatementParams) ([]AccountStatementRow, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreatePosting(ctx context.Context, arg CreatePostingParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) error
	// currency lives on each posting now (ADR-014), not here: an FX transaction
	// spans two currencies, so there is no single transaction-level value left to
	// store. The fx_* columns are the immutable snapshot of the conversion
	// actually applied; all nullable, since a single-currency transaction (still
	// the common case) has none of this.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	// The latest quote for (base, quote) at or before now, preferring a
	// tenant-specific row over the global default (Task 2.4, audit A3.3):
	// tenant_id = $1 matches the tenant's own rows, and tenant_id IS NULL always
	// matches the global default, so a tenant with no row of its own still
	// resolves the global one. ORDER BY (tenant_id IS NULL) sorts a tenant-owned
	// row (false, i.e. 0) ahead of a global row (true, i.e. 1), so when both
	// exist the tenant's own wins regardless of which is more recently
	// effective; effective_at DESC, id DESC is then the same "latest, ties
	// broken by insertion order" tiebreak CurrentFXRate always used, applied
	// within whichever tier (tenant-owned or global) won.
	CurrentFXRate(ctx context.Context, arg CurrentFXRateParams) (FxRate, error)
	// Joins tenants so the resolver gets the tenant's current status alongside
	// the key in the same round trip (Task 2.1, ADR-015): gating needs no extra
	// query. The join is safe against a dangling reference: api_keys_tenant_fk
	// (migration 0011) guarantees every api_keys row's tenant_id has a tenants
	// row. scopes, expires_at, and last_used_at (Task 2.2) are returned as-is:
	// expiry and scope enforcement happen in the resolver and the transport
	// middleware, not in this query.
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	// Raw fetch by id, unfiltered by revoked_at: the admin surface (Task 2.2b)
	// uses this to look up an existing key (including an already-revoked one) by
	// id, for example to copy a key's tenant/name/scopes when rotating it. It
	// does not join tenants: callers that need the tenant's current status look
	// it up separately via GetTenant.
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (GetAPIKeyByIDRow, error)
	GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error)
	// The tenant's most recent row_hash, used to extend the per-tenant hash chain.
	// A fresh tenant (or one with no rows yet) surfaces as pgx.ErrNoRows; the
	// caller treats that as the chain's genesis (domain.AuditGenesisHash).
	GetLastAuditHash(ctx context.Context, tenantID uuid.UUID) (pgtype.Text, error)
	// The per-tenant per-currency FX clearing account (ADR-014, is_system=true),
	// created lazily on first use. Keyed by (tenant_id, name): name is the
	// reserved, deterministic "fx.clearing.<CURRENCY>" string the caller builds,
	// so a second call for the same tenant and currency always resolves to the
	// same row instead of creating a duplicate. The ON CONFLICT arbiter is the
	// partial unique index accounts_system_name_uniq (migration 0010), which only
	// covers is_system rows, so this can never collide with an ordinary
	// user-named account.
	//
	// On conflict this does a no-op DO UPDATE (id set to its own current value)
	// rather than DO NOTHING. DO NOTHING never RETURNs the conflicting row, which
	// an earlier version of this query worked around with a CTE plus a fallback
	// SELECT unioned into the same statement, guarded by NOT EXISTS. That
	// fallback ran against the single statement's original snapshot: when two
	// callers raced to create the same tenant's first clearing account for a
	// currency, the loser blocked on the conflict, and by the time it unblocked
	// (after the winner committed) its own fallback SELECT could still miss the
	// now-committed row, since the snapshot predated that commit. Both branches
	// of the UNION then returned zero rows to the loser, surfacing as "no rows in
	// result set" under concurrent Converts targeting the same pair. DO UPDATE
	// instead forces Postgres's own EvalPlanQual re-fetch of the current row
	// version as part of resolving the conflict, so RETURNING always yields
	// exactly one row, new or existing, in a single round trip with no second
	// snapshot to race against.
	GetOrCreateClearingAccount(ctx context.Context, arg GetOrCreateClearingAccountParams) (GetOrCreateClearingAccountRow, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error)
	// scopes and expires_at (Task 2.2b) are now written on insert: the admin
	// surface (internal/admin) is what actually sets them to something other
	// than the column default. Every pre-2.2b caller (cmd/server's demo and
	// load-test key provisioning, and every repository test that predates
	// scopes) still works unchanged, because the Go-level repository method
	// defaults an empty Scopes slice to {read,post} before it ever reaches this
	// query, the same default the api_keys.scopes column itself carries.
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	// fx_rates is append-only (ADR-014): a new quote is a new row, never an
	// update, so every rate ever applied to a transaction stays reconstructible.
	// tenant_id NULL makes this the global default rate for the pair; a non-NULL
	// tenant_id makes it that tenant's own rate (Task 2.4, audit A3.3), resolved
	// ahead of the global default by CurrentFXRate below.
	//
	// effective_at is a nullable named param (sqlc.narg): when the caller omits
	// an explicit effective_at, COALESCE falls through to the DATABASE SERVER's
	// now(), never the calling process's clock. Stamping an "immediate" rate
	// with the caller's clock is what caused a real clock-skew bug (Task 2.4
	// remediation): CurrentFXRate below gates on "effective_at <= now()" using
	// the server's clock too, so if the caller's clock ran even slightly ahead,
	// a just-inserted row was transiently invisible and the query silently fell
	// through to the global default. Passing NULL here (rather than the CLI
	// host's time.Now()) makes the two clocks the same clock for the common,
	// unscheduled case; an explicit future effective_at (a scheduled rate) is
	// unaffected, since the caller still supplies it directly.
	InsertFXRate(ctx context.Context, arg InsertFXRateParams) (FxRate, error)
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	// Every key for a tenant, oldest first, including revoked ones: the admin
	// surface's list view (Task 2.2b) is meant to show a tenant's full key
	// history, not just its live keys. Never selects key_hash: plaintext is
	// shown once at issue/rotate time and is never recoverable afterward, and
	// the hash itself has no business leaving the resolver's lookup path.
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAPIKeysByTenantRow, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]ListAccountsRow, error)
	// Keyset page of audit rows for every transaction with a posting touching the
	// account, newest first. after_created_at / after_id are the keyset position:
	// pass a far-future timestamp and the max uuid for the first page.
	ListAuditByAccount(ctx context.Context, arg ListAuditByAccountParams) ([]AuditLog, error)
	ListAuditByTransaction(ctx context.Context, arg ListAuditByTransactionParams) ([]AuditLog, error)
	// Every audit row for the tenant, oldest first: the full walk used to
	// recompute and check the tamper-evident hash chain end to end.
	ListAuditForVerify(ctx context.Context, tenantID uuid.UUID) ([]AuditLog, error)
	ListPostingsByTransaction(ctx context.Context, arg ListPostingsByTransactionParams) ([]ListPostingsByTransactionRow, error)
	ListTenants(ctx context.Context, limit int32) ([]Tenant, error)
	// COALESCE makes this idempotent: revoking an already-revoked key keeps its
	// original revoked_at instead of bumping it, and still reports one row
	// affected (not zero), so the admin service can tell "no such key" (0 rows)
	// from "already revoked" (1 row, unchanged) without a separate lookup.
	RevokeAPIKey(ctx context.Context, id uuid.UUID) (int64, error)
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (int64, error)
	// Updates last_used_at for a single key by id. Called best-effort and
	// throttled from the auth resolver (Task 2.2): not every request, so this is
	// not a write on the hot path of every authenticated call.
	TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error
}

var _ Querier = (*Queries)(nil)
