// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const trialBalanceAccounts = `-- name: TrialBalanceAccounts :many
SELECT a.id, a.name, a.type, a.currency, a.is_system,
       COALESCE(SUM(p.amount), 0)::bigint AS balance
FROM accounts a
LEFT JOIN postings p ON p.tenant_id = a.tenant_id AND p.account_id = a.id
WHERE a.tenant_id = $1
GROUP BY a.id, a.name, a.type, a.currency, a.is_system
ORDER BY a.name, a.id
`

type TrialBalanceAccountsRow struct {
	ID       uuid.UUID
	Name     string
	Type     string
	Currency string
	IsSystem bool
	Balance  int64
}

// Task 6.3, audit A9.2: every account's derived balance, including system
// (FX clearing) accounts, which hold the FX position and are part of the
// balance proof. The LEFT JOIN means an account with no postings yet still
// returns one row, with balance COALESCEd to 0, the same shape
// AccountBalances (postings.sql) already uses.
func (q *Queries) TrialBalanceAccounts(ctx context.Context, tenantID uuid.UUID) ([]TrialBalanceAccountsRow, error) {
	rows, err := q.db.Query(ctx, trialBalanceAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialBalanceAccountsRow
	for rows.Next() {
		var i TrialBalanceAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.IsSystem,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trialBalanceByCurrency = `-- name: TrialBalanceByCurrency :many
SELECT currency, SUM(amount)::bigint AS net
FROM postings
WHERE tenant_id = $1
GROUP BY currency
`

type TrialBalanceByCurrencyRow struct {
	Currency string
	Net      int64
}

// Task 6.3, audit A9.2: the double-entry balance proof. Each currency's net
// posted total across every account in the tenant; in a correct ledger every
// total is zero (ADR-001).
func (q *Queries) TrialBalanceByCurrency(ctx context.Context, tenantID uuid.UUID) ([]TrialBalanceByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, trialBalanceByCurrency, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialBalanceByCurrencyRow
	for rows.Next() {
		var i TrialBalanceByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.Net); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
