// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :exec
INSERT INTO tenants (id, name) VALUES ($1, $2)
`

type CreateTenantParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) error {
	_, err := q.db.Exec(ctx, createTenant, arg.ID, arg.Name)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, status, settings, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, status, settings, created_at FROM tenants ORDER BY created_at, id LIMIT $1
`

func (q *Queries) ListTenants(ctx context.Context, limit int32) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantStatus = `-- name: SetTenantStatus :execrows
UPDATE tenants SET status = $2 WHERE id = $1
`

type SetTenantStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setTenantStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
