// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (id, tenant_id, currency)
VALUES ($1, $2, $3)
`

type CreateTransactionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Currency string
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction, arg.ID, arg.TenantID, arg.Currency)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, tenant_id, currency, created_at
FROM transactions
WHERE tenant_id = $1 AND id = $2
`

type GetTransactionParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.TenantID, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
