// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, tenant_id, subscription_id, audit_chain_seq, event_type, payload, status, attempts, next_attempt_at, last_error, created_at, delivered_at
FROM webhook_deliveries
WHERE id = $1
`

// Raw fetch by id: tests and any future delivery-inspection tooling read a
// single row's full lifecycle state back this way.
func (q *Queries) GetWebhookDelivery(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.AuditChainSeq,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastError,
		&i.CreatedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getWebhookFanoutCursorForUpdate = `-- name: GetWebhookFanoutCursorForUpdate :one
SELECT last_chain_seq FROM webhook_fanout_cursor FOR UPDATE
`

// Reads the singleton fan-out cursor and locks its row for the rest of the
// surrounding transaction (Task 4.1): the same "read the watermark, then
// act, all in one transaction" shape ADR-017's chainer uses for audit_log,
// so the cursor read and its eventual advance (SetWebhookFanoutCursor) never
// race a concurrent fan-out pass.
func (q *Queries) GetWebhookFanoutCursorForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getWebhookFanoutCursorForUpdate)
	var last_chain_seq int64
	err := row.Scan(&last_chain_seq)
	return last_chain_seq, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :execrows
INSERT INTO webhook_deliveries (id, tenant_id, subscription_id, audit_chain_seq, event_type, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subscription_id, audit_chain_seq) DO NOTHING
`

type InsertWebhookDeliveryParams struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SubscriptionID uuid.UUID
	AuditChainSeq  int64
	EventType      string
	Payload        []byte
}

// Creates one fan-out row for a (subscription, audit event) pairing. The
// ON CONFLICT DO NOTHING against the UNIQUE (subscription_id,
// audit_chain_seq) index (migration 0021) is what makes fan-out
// exactly-once into this table even if the fan-out step ever ran twice over
// the same audit_log range: a repeat attempt is a silent no-op, not a
// duplicate delivery row, so execrows reports 0 for a pairing that already
// existed and 1 for a genuinely new one.
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.AuditChainSeq,
		arg.EventType,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertWebhookSubscription = `-- name: InsertWebhookSubscription :exec
INSERT INTO webhook_subscriptions (id, tenant_id, url, secret, event_types)
VALUES ($1, $2, $3, $4, $5)
`

type InsertWebhookSubscriptionParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Secret     string
	EventTypes []string
}

// Inserts a new webhook_subscriptions row, always active (a caller creates a
// subscription to receive events; deactivating happens later, via
// SetWebhookSubscriptionActive). secret is stored as-is, never hashed (Task
// 4.1, audit A7.1): the delivery worker must read it back in full to sign
// every outbound payload.
func (q *Queries) InsertWebhookSubscription(ctx context.Context, arg InsertWebhookSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertWebhookSubscription,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.EventTypes,
	)
	return err
}

const listActiveWebhookSubscriptionsByTenant = `-- name: ListActiveWebhookSubscriptionsByTenant :many
SELECT id, tenant_id, url, secret, event_types
FROM webhook_subscriptions
WHERE tenant_id = $1 AND active
ORDER BY id
`

type ListActiveWebhookSubscriptionsByTenantRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	Secret     string
	EventTypes []string
}

// The fan-out step's per-tenant read (Task 4.1): every ACTIVE subscription
// for one tenant, including the secret and event_types the fan-out needs to
// decide whether and how to create a webhook_deliveries row for it. Ordered
// by id only for a stable, deterministic iteration order within one fan-out
// pass; it carries no meaning beyond that.
func (q *Queries) ListActiveWebhookSubscriptionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListActiveWebhookSubscriptionsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveWebhookSubscriptionsByTenantRow
	for rows.Next() {
		var i ListActiveWebhookSubscriptionsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.EventTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogSinceChainSeq = `-- name: ListAuditLogSinceChainSeq :many
SELECT chain_seq, tenant_id, action, transaction_id, subject_type, subject_id, after, created_at
FROM audit_log
WHERE chain_seq > $1
ORDER BY chain_seq
LIMIT $2
`

type ListAuditLogSinceChainSeqParams struct {
	AfterSeq   int64
	BatchLimit int32
}

type ListAuditLogSinceChainSeqRow struct {
	ChainSeq      int64
	TenantID      uuid.UUID
	Action        string
	TransactionID pgtype.UUID
	SubjectType   pgtype.Text
	SubjectID     pgtype.UUID
	After         []byte
	CreatedAt     time.Time
}

// The fan-out step's source read: every chained audit_log event past the
// cursor, oldest first, up to batch_limit. Reads chain_seq (ADR-017's
// failover-safe, skew-proof linearization key), not id or created_at, for
// the same reason GetLastAuditHash does: it is the one order the chainer
// itself guarantees is monotonic across any failover.
//
// transaction_id is nullable (ADR-025, migration 0034): a chained
// non-transaction lifecycle event (for example approval.rejected) has none.
// The fan-out worker maps a null transaction_id to an empty, omitted field
// in the webhook payload, the same convention the rest of the audit read
// path uses. subject_type/subject_id (also ADR-025) are what that kind of
// event carries instead: the fan-out worker copies them onto the payload
// (Task 10) so a consumer can tell which subject the event concerns.
func (q *Queries) ListAuditLogSinceChainSeq(ctx context.Context, arg ListAuditLogSinceChainSeqParams) ([]ListAuditLogSinceChainSeqRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogSinceChainSeq, arg.AfterSeq, arg.BatchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogSinceChainSeqRow
	for rows.Next() {
		var i ListAuditLogSinceChainSeqRow
		if err := rows.Scan(
			&i.ChainSeq,
			&i.TenantID,
			&i.Action,
			&i.TransactionID,
			&i.SubjectType,
			&i.SubjectID,
			&i.After,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueWebhookDeliveries = `-- name: ListDueWebhookDeliveries :many
SELECT wd.id, wd.tenant_id, wd.subscription_id, wd.event_type, wd.payload, wd.attempts,
       ws.url, ws.secret
FROM webhook_deliveries wd
JOIN webhook_subscriptions ws ON ws.id = wd.subscription_id
WHERE wd.status IN ('pending', 'failed') AND wd.next_attempt_at <= now() AND ws.active
ORDER BY wd.next_attempt_at
LIMIT $1
FOR UPDATE OF wd SKIP LOCKED
`

type ListDueWebhookDeliveriesRow struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SubscriptionID uuid.UUID
	EventType      string
	Payload        []byte
	Attempts       int32
	Url            string
	Secret         string
}

// The delivery worker's batch read: pending/failed rows whose backoff has
// elapsed, oldest due first, joined to their subscription for the url and
// secret needed to sign and send. "AND ws.active" means a subscription that
// was deactivated after fan-out already created pending rows for it simply
// stops being picked up here (see SetWebhookSubscriptionActive's doc
// comment): its existing rows are left exactly as they are, neither
// delivered nor purged, just never attempted again. FOR UPDATE OF wd SKIP
// LOCKED is defense in depth against two workers ever running at once (the
// leader-election lock is what actually prevents that in normal operation,
// ADR-017's discipline mirrored for this worker): a second reader skips a
// row the first is mid-processing rather than picking it up concurrently.
// This query runs as its own standalone statement (never inside a
// surrounding transaction that also makes the outbound HTTP call), so the
// row lock is released the moment this statement completes; correctness
// does not depend on holding it any longer than that.
func (q *Queries) ListDueWebhookDeliveries(ctx context.Context, batchLimit int32) ([]ListDueWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listDueWebhookDeliveries, batchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueWebhookDeliveriesRow
	for rows.Next() {
		var i ListDueWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
			&i.Url,
			&i.Secret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveriesBySubscription = `-- name: ListWebhookDeliveriesBySubscription :many
SELECT id, tenant_id, subscription_id, audit_chain_seq, event_type, payload, status, attempts, next_attempt_at, last_error, created_at, delivered_at
FROM webhook_deliveries
WHERE subscription_id = $1
ORDER BY audit_chain_seq
`

// Every delivery row for one subscription, in fan-out order (the same
// chain_seq order the source audit_log events were read in). Used by tests
// to assert fan-out and delivery outcomes end to end.
func (q *Queries) ListWebhookDeliveriesBySubscription(ctx context.Context, subscriptionID uuid.UUID) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveriesBySubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.AuditChainSeq,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastError,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptionsByTenant = `-- name: ListWebhookSubscriptionsByTenant :many
SELECT id, tenant_id, url, event_types, active, created_at
FROM webhook_subscriptions
WHERE tenant_id = $1
ORDER BY created_at, id
`

type ListWebhookSubscriptionsByTenantRow struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Url        string
	EventTypes []string
	Active     bool
	CreatedAt  time.Time
}

// Every subscription for a tenant, oldest first, active or not: the admin
// surface's list view. Never selects secret: it is shown once, at creation
// time, and never recoverable through a list call.
func (q *Queries) ListWebhookSubscriptionsByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListWebhookSubscriptionsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptionsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookSubscriptionsByTenantRow
	for rows.Next() {
		var i ListWebhookSubscriptionsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.EventTypes,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookDeliveryDelivered = `-- name: MarkWebhookDeliveryDelivered :execrows
UPDATE webhook_deliveries SET status = 'delivered', delivered_at = now(), attempts = $1
WHERE id = $2 AND status IN ('pending', 'failed')
`

type MarkWebhookDeliveryDeliveredParams struct {
	Attempts int32
	ID       uuid.UUID
}

// A 2xx response: terminal success. attempts is set to the total number of
// tries this delivery took (including the successful one), the same total
// MarkWebhookDeliveryFailed accumulates on the way here, so attempts always
// means "how many times this delivery was actually tried", not just "how
// many times it failed". "AND status IN ('pending', 'failed')" guards
// against a state regression: in a two-leader window (SKIP LOCKED is
// defense in depth, not a guarantee, see ListDueWebhookDeliveries) two
// workers can pick up the same due row, and without this guard a slower
// worker's write could still land after a faster worker already reached a
// terminal outcome for it. Once a row is 'delivered' or 'dead', neither mark
// query can move it again: this returns 0 affected rows instead, which the
// caller (internal/webhook) treats as a no-op, not an error.
func (q *Queries) MarkWebhookDeliveryDelivered(ctx context.Context, arg MarkWebhookDeliveryDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookDeliveryDelivered, arg.Attempts, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markWebhookDeliveryFailed = `-- name: MarkWebhookDeliveryFailed :execrows
UPDATE webhook_deliveries
SET status = $1, attempts = $2, next_attempt_at = $3, last_error = $4
WHERE id = $5 AND status IN ('pending', 'failed')
`

type MarkWebhookDeliveryFailedParams struct {
	Status        string
	Attempts      int32
	NextAttemptAt time.Time
	LastError     pgtype.Text
	ID            uuid.UUID
}

// A non-2xx response or transport error: the caller (internal/webhook)
// computes the new attempts count, the resulting status ('failed' to retry
// again later, or 'dead' once attempts reaches the configured max), the next
// backoff deadline, and the error text to record, all in Go (backoff and the
// max-attempts cap are application config, not schema), and this query just
// persists that decision. "AND status IN ('pending', 'failed')" is the same
// terminal-state guard MarkWebhookDeliveryDelivered carries (see its doc
// comment): a delivery already 'delivered' (or already 'dead') can never be
// regressed by a late failure write from a second worker that raced this one.
func (q *Queries) MarkWebhookDeliveryFailed(ctx context.Context, arg MarkWebhookDeliveryFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markWebhookDeliveryFailed,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.LastError,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWebhookFanoutCursor = `-- name: SetWebhookFanoutCursor :exec
UPDATE webhook_fanout_cursor SET last_chain_seq = $1
`

// Advances the singleton fan-out cursor. Always called in the same
// transaction as the webhook_deliveries inserts it corresponds to (Task
// 4.1), so a crash between the two is impossible: either both the inserts
// and the cursor advance land, or neither does, and a retried fan-out pass
// sees the same audit_log rows again (harmless: InsertWebhookDelivery's
// ON CONFLICT DO NOTHING against the (subscription_id, audit_chain_seq)
// unique index makes re-inserting the same pairing a no-op).
func (q *Queries) SetWebhookFanoutCursor(ctx context.Context, lastChainSeq int64) error {
	_, err := q.db.Exec(ctx, setWebhookFanoutCursor, lastChainSeq)
	return err
}

const setWebhookSubscriptionActive = `-- name: SetWebhookSubscriptionActive :execrows
UPDATE webhook_subscriptions SET active = $1 WHERE id = $2
`

type SetWebhookSubscriptionActiveParams struct {
	Active bool
	ID     uuid.UUID
}

// Flips active for one subscription by id. The admin surface's
// DeleteSubscription calls this with active=false instead of a hard DELETE
// (see domain.Repository.SetWebhookSubscriptionActive's doc comment for
// why): a webhook_deliveries row's foreign key to its subscription has no
// cascade, so deactivating, not deleting, is what "stops future deliveries"
// without breaking or discarding delivery history.
func (q *Queries) SetWebhookSubscriptionActive(ctx context.Context, arg SetWebhookSubscriptionActiveParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWebhookSubscriptionActive, arg.Active, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
